import { PlaybackConfig, SpeedMode, SentenceItem } from './types';

export const MODE_CONFIGS: Record<SpeedMode, PlaybackConfig> = {
  [SpeedMode.FAST]: { rate: 1.2, postDelayMs: 500 },
  [SpeedMode.NORMAL]: { rate: 1.0, postDelayMs: 1200 },
  [SpeedMode.SLOW]: { rate: 0.8, postDelayMs: 2000 },
};

export const SENTENCE_DATA: SentenceItem[] = [
  { french: "Je suis japonais.", english: "I am Japanese.", audio: "001_Je_suis_japonais..wav" },
  { french: "Je suis anglais.", english: "I am English.", audio: "002_Je_suis_anglais..wav" },
  { french: "Tu es français ?", english: "Are you French?", audio: "003_Tu_es_français.wav" },
  { french: "Tu es étudiant ?", english: "Are you a student?", audio: "004_Tu_es_étudiant.wav" },
  { french: "Il est grand.", english: "He is tall.", audio: "005_Il_est_grand..wav" },
  { french: "Elle est grande.", english: "She is tall.", audio: "006_Elle_est_grande..wav" },
  { french: "Paul et Marie sont étudiants.", english: "Paul and Marie are students.", audio: "007_Paul_et_Marie_sont_étudiants..wav" },
  { french: "Ils sont des étudiants.", english: "They are students.", audio: "008_Ils_sont_des_étudiants..wav" },
  { french: "Elles sont heureuses.", english: "They are happy.", audio: "009_Elles_sont_heureuses..wav" },
  { french: "Vous êtes bien ?", english: "Are you comfortable?", audio: "010_Vous_êtes_bien.wav" },
  { french: "J'ai une voiture.", english: "I have a car.", audio: "011_J'ai_une_voiture..wav" },
  { french: "Tu as quel âge ?", english: "How old are you?", audio: "012_Tu_as_quel_âge.wav" },
  { french: "Elle a beaucoup de livres.", english: "She has a lot of books.", audio: "013_Elle_a_beaucoup_de_livres..wav" },
  { french: "Ils ont un chat.", english: "They have a cat.", audio: "014_Ils_ont_un_chat..wav" },
  { french: "On a faim.", english: "We are hungry.", audio: "015_On_a_faim..wav" },
  { french: "On a un chien.", english: "We have a dog.", audio: "016_On_a_un_chien..wav" },
  { french: "Nous parlons le français.", english: "We speak French.", audio: "017_Nous_parlons_le_français..wav" },
  { french: "Nous étudions le français.", english: "We study French.", audio: "018_Nous_étudions_le_français..wav" },
  { french: "Nous mangeons.", english: "We are eating.", audio: "019_Nous_mangeons..wav" },
  { french: "Tu aimes le chocolat ?", english: "Do you like chocolate?", audio: "020_Tu_aimes_le_chocolat.wav" },
  { french: "Elles aiment la musique.", english: "They like music.", audio: "021_Elles_aiment_la_musique..wav" },
  { french: "Il ne parle pas anglais.", english: "He does not speak English.", audio: "022_Il_ne_parle_pas_anglais..wav" },
  { french: "Il finit son travail.", english: "He finishes his work.", audio: "023_Il_finit_son_travail..wav" },
  { french: "Nous finissons le travail.", english: "We finish the work.", audio: "024_Nous_finissons_le_travail..wav" },
  { french: "Tu finis tes devoirs ?", english: "Are you finishing your homework?", audio: "025_Tu_finis_tes_devoirs.wav" },
  { french: "Nous choisissons ce film.", english: "We choose this movie.", audio: "026_Nous_choisissons_ce_film..wav" },
  { french: "Je vais à Paris.", english: "I am going to Paris.", audio: "027_Je_vais_à_Paris..wav" },
  { french: "Je vais au Canada.", english: "I am going to Canada.", audio: "028_Je_vais_au_Canada..wav" },
  { french: "Je vais au Brésil.", english: "I am going to Brazil.", audio: "029_Je_vais_au_Brésil..wav" },
  { french: "Je vais en France.", english: "I am going to France.", audio: "030_Je_vais_en_France..wav" },
  { french: "Je vais aux États-Unis.", english: "I am going to the United States.", audio: "031_Je_vais_aux_États-Unis..wav" },
  { french: "Je vais aux toilettes.", english: "I am going to the restroom.", audio: "032_Je_vais_aux_toilettes..wav" },
  { french: "Nous allons au musée.", english: "We are going to the museum.", audio: "033_Nous_allons_au_musée..wav" },
  { french: "Nous allons à la gare.", english: "We are going to the train station.", audio: "034_Nous_allons_à_la_gare..wav" },
  { french: "Vous allez où ?", english: "Where are you going?", audio: "035_Vous_allez_où.wav" },
  { french: "Ils vont au Canada.", english: "They are going to Canada.", audio: "036_Ils_vont_au_Canada..wav" },
  { french: "On va au cinéma.", english: "We are going to the movies.", audio: "037_On_va_au_cinéma..wav" },
  { french: "On va bien.", english: "We are doing well.", audio: "038_On_va_bien..wav" },
  { french: "Je viens de Tokyo.", english: "I come from Tokyo.", audio: "039_Je_viens_de_Tokyo..wav" },
  { french: "Je viens de France.", english: "I come from France.", audio: "040_Je_viens_de_France..wav" },
  { french: "Je viens du Japon.", english: "I come from Japan.", audio: "041_Je_viens_du_Japon..wav" },
  { french: "Je viens du Canada.", english: "I come from Canada.", audio: "042_Je_viens_du_Canada..wav" },
  { french: "Je viens du Brésil.", english: "I come from Brazil.", audio: "043_Je_viens_du_Brésil..wav" },
  { french: "Je viens du Chili.", english: "I come from Chile.", audio: "044_Je_viens_du_Chili..wav" },
  { french: "Je viens des États-Unis.", english: "I come from the United States.", audio: "045_Je_viens_des_États-Unis..wav" },
  { french: "Ils viennent de France.", english: "They come from France.", audio: "046_Ils_viennent_de_France..wav" },
  { french: "Ils viennent des États-Unis.", english: "They come from the United States.", audio: "047_Ils_viennent_des_États-Unis..wav" },
  { french: "Vous venez du Japon ?", english: "Do you come from Japan?", audio: "048_Vous_venez_du_Japon.wav" },
  { french: "La chemise est blanche.", english: "The shirt is white.", audio: "049_La_chemise_est_blanche..wav" },
  { french: "Les maisons sont grandes.", english: "The houses are big.", audio: "050_Les_maisons_sont_grandes..wav" },
  { french: "Les fleurs sont rouges.", english: "The flowers are red.", audio: "051_Les_fleurs_sont_rouges..wav" },
  { french: "Ils sont contents.", english: "They are happy.", audio: "052_Ils_sont_contents..wav" },
  { french: "C'est un bel appartement.", english: "It's a beautiful apartment.", audio: "053_C'est_un_bel_appartement..wav" },
  { french: "Ce sont de beaux jardins.", english: "These are beautiful gardens.", audio: "054_Ce_sont_de_beaux_jardins..wav" },
  { french: "C'est mon école.", english: "It's my school.", audio: "055_C'est_mon_école..wav" },
  { french: "C'est mon amie.", english: "She is my friend.", audio: "056_C'est_mon_amie..wav" },
  { french: "C'est ton amie ?", english: "Is she your friend?", audio: "057_C'est_ton_amie.wav" },
  { french: "C'est son histoire.", english: "It's his story.", audio: "058_C'est_son_histoire..wav" },
  { french: "C'est mon père.", english: "He is my father.", audio: "059_C'est_mon_père..wav" },
  { french: "C'est mon stylo.", english: "It's my pen.", audio: "060_C'est_mon_stylo..wav" },
  { french: "Ce sont mes voitures.", english: "These are my cars.", audio: "061_Ce_sont_mes_voitures..wav" },
  { french: "Regardez cet arbre.", english: "Look at this tree.", audio: "062_Regardez_cet_arbre..wav" },
  { french: "C'est cet hôtel.", english: "It's this hotel.", audio: "063_C'est_cet_hôtel..wav" },
  { french: "Ce sont ces photos.", english: "These are those photos.", audio: "064_Ce_sont_ces_photos..wav" },
  { french: "C'est ce livre ?", english: "Is it this book?", audio: "065_C'est_ce_livre.wav" },
  { french: "Je n'ai pas de tablette.", english: "I don't have a tablet.", audio: "066_Je_n'ai_pas_de_tablette..wav" },
  { french: "Je n'ai pas de stylo.", english: "I don't have a pen.", audio: "067_Je_n'ai_pas_de_stylo..wav" },
  { french: "Je n'ai pas d'argent.", english: "I don't have money.", audio: "068_Je_n'ai_pas_d'argent..wav" },
  { french: "Je n'ai pas d'amis.", english: "I don't have friends.", audio: "069_Je_n'ai_pas_d'amis..wav" },
  { french: "Il n'y a pas d'eau.", english: "There is no water.", audio: "070_Il_n'y_a_pas_d'eau..wav" },
  { french: "Il n'y a pas de lait.", english: "There is no milk.", audio: "071_Il_n'y_a_pas_de_lait..wav" },
  { french: "Il n'y a pas de problème.", english: "There is no problem.", audio: "072_Il_n'y_a_pas_de_problème..wav" },
  { french: "Nous n'avons pas d'idée.", english: "We have no idea.", audio: "073_Nous_n'avons_pas_d'idée..wav" },
  { french: "Elle ne mange pas de légumes.", english: "She doesn't eat vegetables.", audio: "074_Elle_ne_mange_pas_de_légumes..wav" },
  { french: "Tu ne manges pas d'ananas.", english: "You don't eat pineapples.", audio: "075_Tu_ne_manges_pas_d'ananas..wav" },
  { french: "Il ne boit pas d'alcool.", english: "He doesn't drink alcohol.", audio: "076_Il_ne_boit_pas_d'alcool..wav" },
  { french: "Il n'achète pas d'ordinateur.", english: "He isn't buying a computer.", audio: "077_Il_n'achète_pas_d'ordinateur..wav" },
  { french: "Elle n'a pas d'enfants.", english: "She has no children.", audio: "078_Elle_n'a_pas_d'enfants..wav" },
  { french: "Je n'aime pas le lait.", english: "I don't like milk.", audio: "079_Je_n'aime_pas_le_lait..wav" },
  { french: "Il n'est plus jeune.", english: "He is no longer young.", audio: "080_Il_n'est_plus_jeune..wav" },
  { french: "Elle ne mange jamais de nattô.", english: "She never eats natto.", audio: "081_Elle_ne_mange_jamais_de_nattô..wav" },
  { french: "Ce n'est pas un problème.", english: "It's not a problem.", audio: "082_Ce_n'est_pas_un_problème..wav" },
  { french: "Ce n'est pas un stylo.", english: "It's not a pen.", audio: "083_Ce_n'est_pas_un_stylo..wav" },
  { french: "Ce n'est pas un hôtel.", english: "It's not a hotel.", audio: "084_Ce_n'est_pas_un_hôtel..wav" },
  { french: "Ce n'est pas une école.", english: "It's not a school.", audio: "085_Ce_n'est_pas_une_école..wav" },
  { french: "Ce n'est pas une voiture.", english: "It's not a car.", audio: "086_Ce_n'est_pas_une_voiture..wav" },
  { french: "Ce ne sont pas des étudiants.", english: "They are not students.", audio: "087_Ce_ne_sont_pas_des_étudiants..wav" },
  { french: "Ce ne sont pas des livres.", english: "These are not books.", audio: "088_Ce_ne_sont_pas_des_livres..wav" },
  { french: "Ce ne sont pas des voitures japonaises.", english: "These are not Japanese cars.", audio: "089_Ce_ne_sont_pas_des_voitures_japonaises..wav" },
  { french: "Ce ne sont pas des touristes.", english: "They are not tourists.", audio: "090_Ce_ne_sont_pas_des_touristes..wav" },
  { french: "Je vais sortir.", english: "I am going to go out.", audio: "091_Je_vais_sortir..wav" },
  { french: "Je vais manger.", english: "I am going to eat.", audio: "092_Je_vais_manger..wav" },
  { french: "Je vais visiter Paris.", english: "I am going to visit Paris.", audio: "093_Je_vais_visiter_Paris..wav" },
  { french: "Tu vas partir ce soir ?", english: "Are you leaving tonight?", audio: "094_Tu_vas_partir_ce_soir.wav" },
  { french: "Il va manger le déjeuner.", english: "He is going to eat lunch.", audio: "095_Il_va_manger_le_déjeuner..wav" },
  { french: "Il va prendre un café.", english: "He is going to have a coffee.", audio: "096_Il_va_prendre_un_café..wav" },
  { french: "Elle va prendre le train.", english: "She is going to take the train.", audio: "097_Elle_va_prendre_le_train..wav" },
  { french: "Elle va prendre le bus.", english: "She is going to take the bus.", audio: "098_Elle_va_prendre_le_bus..wav" },
  { french: "Nous allons acheter une voiture.", english: "We are going to buy a car.", audio: "099_Nous_allons_acheter_une_voiture..wav" },
  { french: "Nous allons étudier le français.", english: "We are going to study French.", audio: "100_Nous_allons_étudier_le_français..wav" },
  { french: "Vous allez comprendre.", english: "You are going to understand.", audio: "101_Vous_allez_comprendre..wav" },
  { french: "Vous allez écouter la radio.", english: "You are going to listen to the radio.", audio: "102_Vous_allez_écouter_la_radio..wav" },
  { french: "Vous allez partir ?", english: "Are you going to leave?", audio: "103_Vous_allez_partir.wav" },
  { french: "Ils vont arriver bientôt.", english: "They are going to arrive soon.", audio: "104_Ils_vont_arriver_bientôt..wav" },
  { french: "On va partir bientôt.", english: "We are going to leave soon.", audio: "105_On_va_partir_bientôt..wav" },
  { french: "On va manger ce soir.", english: "We are going to eat tonight.", audio: "106_On_va_manger_ce_soir..wav" },
  { french: "On va sortir.", english: "We are going to go out.", audio: "107_On_va_sortir..wav" },
  { french: "Nous venons d'arriver à Bordeaux.", english: "We just arrived in Bordeaux.", audio: "108_Nous_venons_d'arriver_à_Bordeaux..wav" },
  { french: "Nous venons de manger.", english: "We just ate.", audio: "109_Nous_venons_de_manger..wav" },
  { french: "Nous venons de partir.", english: "We just left.", audio: "110_Nous_venons_de_partir..wav" },
  { french: "Quel âge a-t-il ?", english: "How old is he?", audio: "111_Quel_âge_a-t-il.wav" },
  { french: "Quel temps fait-il ?", english: "What is the weather like?", audio: "112_Quel_temps_fait-il.wav" },
  { french: "Quel est votre nom ?", english: "What is your name?", audio: "113_Quel_est_votre_nom.wav" },
  { french: "Quelle est votre profession ?", english: "What is your profession?", audio: "114_Quelle_est_votre_profession.wav" },
  { french: "Quelle est votre nationalité ?", english: "What is your nationality?", audio: "115_Quelle_est_votre_nationalité.wav" },
  { french: "Quelle heure est-il ?", english: "What time is it?", audio: "116_Quelle_heure_est-il.wav" },
  { french: "Quelles fleurs sont sur la table ?", english: "Which flowers are on the table?", audio: "117_Quelles_fleurs_sont_sur_la_table.wav" },
  { french: "Combien coûte ce livre ?", english: "How much does this book cost?", audio: "118_Combien_coûte_ce_livre.wav" },
  { french: "Où habitez-vous ?", english: "Where do you live?", audio: "119_Où_habitez-vous.wav" },
  { french: "Quand partez-vous ?", english: "When are you leaving?", audio: "120_Quand_partez-vous.wav" },
  { french: "Est-ce que tu parles français ?", english: "Do you speak French?", audio: "121_Est-ce_que_tu_parles_français.wav" },
  { french: "Voyage-t-il au Japon ?", english: "Is he traveling to Japan?", audio: "122_Voyage-t-il_au_Japon.wav" },
  { french: "Va à l'école.", english: "Go to school.", audio: "123_Va_à_l'école..wav" },
  { french: "Parle un peu.", english: "Speak a little.", audio: "124_Parle_un_peu..wav" },
  { french: "Parle français !", english: "Speak French!", audio: "125_Parle_français.wav" },
  { french: "Regarde cette fleur !", english: "Look at this flower!", audio: "126_Regarde_cette_fleur.wav" },
  { french: "Regardez ces photos.", english: "Look at these photos.", audio: "127_Regardez_ces_photos..wav" },
  { french: "Regardez cette photo.", english: "Look at this photo.", audio: "128_Regardez_cette_photo..wav" },
  { french: "Soyez calmes !", english: "Be calm!", audio: "129_Soyez_calmes.wav" },
  { french: "Allons au cinéma !", english: "Let's go to the movies!", audio: "130_Allons_au_cinéma.wav" },
  { french: "Allons au restaurant !", english: "Let's go to the restaurant!", audio: "131_Allons_au_restaurant.wav" },
  { french: "Écoutons la musique !", english: "Let's listen to music!", audio: "132_Écoutons_la_musique.wav" },
  { french: "C'est très bon.", english: "It's very good.", audio: "133_C'est_très_bon..wav" },
  { french: "C'est un hôtel.", english: "It's a hotel.", audio: "134_C'est_un_hôtel..wav" },
  { french: "Ce sont des stylos.", english: "These are pens.", audio: "135_Ce_sont_des_stylos..wav" },
  { french: "Il est dix heures.", english: "It is ten o'clock.", audio: "136_Il_est_dix_heures..wav" },
  { french: "Il fait beau.", english: "The weather is nice.", audio: "137_Il_fait_beau..wav" },
  { french: "Il fait chaud.", english: "It is hot.", audio: "138_Il_fait_chaud..wav" },
  { french: "Il y a du vent.", english: "It is windy.", audio: "139_Il_y_a_du_vent..wav" },
  { french: "Il neige.", english: "It is snowing.", audio: "140_Il_neige..wav" },
  { french: "Il est plus grand que moi.", english: "He is taller than me.", audio: "141_Il_est_plus_grand_que_moi..wav" },
  { french: "Je vais au cinéma avec lui.", english: "I am going to the movies with him.", audio: "142_Je_vais_au_cinéma_avec_lui..wav" },
  { french: "Si, j'ai faim.", english: "Yes, I am hungry.", audio: "143_Si,_j'ai_faim..wav" },
  { french: "Je parle aux étudiants.", english: "I am talking to the students.", audio: "144_Je_parle_aux_étudiants..wav" },
  { french: "C'est la voiture du père.", english: "It's the father's car.", audio: "145_C'est_la_voiture_du_père..wav" },
  { french: "C'est le frère de Paul.", english: "It's Paul's brother.", audio: "146_C'est_le_frère_de_Paul..wav" },
  { french: "Je rentre du bureau.", english: "I am coming back from the office.", audio: "147_Je_rentre_du_bureau..wav" },
  { french: "C'est un vin du Chili.", english: "It's a wine from Chile.", audio: "148_C'est_un_vin_du_Chili..wav" },
  { french: "Je finis mon travail à cinq heures.", english: "I finish my work at five o'clock.", audio: "149_Je_finis_mon_travail_à_cinq_heures..wav" },
  { french: "Mon frère grandit de jour en jour.", english: "My brother is growing day by day.", audio: "150_Mon_frère_grandit_de_jour_en_jour..wav" },
  { french: "ce jardin", english: "this garden", audio: "151_ce_jardin.wav" },
  { french: "cet arbre", english: "this tree", audio: "152_cet_arbre.wav" },
  { french: "cette fleur", english: "this flower", audio: "153_cette_fleur.wav" },
  { french: "ces jardins", english: "these gardens", audio: "154_ces_jardins.wav" },
  { french: "ces arbres", english: "these trees", audio: "155_ces_arbres.wav" },
  { french: "ces fleurs", english: "these flowers", audio: "156_ces_fleurs.wav" },
  { french: "cet hôtel", english: "this hotel", audio: "157_cet_hôtel.wav" },
  { french: "ce livre-ci", english: "this book", audio: "158_ce_livre-ci.wav" },
  { french: "ce livre-là", english: "that book", audio: "159_ce_livre-là.wav" },
  { french: "mon père", english: "my father", audio: "160_mon_père.wav" },
  { french: "ta mère", english: "your mother", audio: "161_ta_mère.wav" },
  { french: "ses parents", english: "his/her parents", audio: "162_ses_parents.wav" },
  { french: "mon amie", english: "my friend", audio: "163_mon_amie.wav" },
  { french: "ton école", english: "your school", audio: "164_ton_école.wav" },
  { french: "son histoire", english: "his/her story", audio: "165_son_histoire.wav" },
  { french: "Je suis français.", english: "I am French.", audio: "166_Je_suis_français..wav" },
  { french: "Et toi ?", english: "And you?", audio: "167_Et_toi.wav" },
  { french: "Moi aussi.", english: "Me too.", audio: "168_Moi_aussi..wav" },
  { french: "C'est Théo ?", english: "Is that Théo?", audio: "169_C'est_Théo.wav" },
  { french: "Oui, c'est lui.", english: "Yes, it is him.", audio: "170_Oui,_c'est_lui..wav" },
  { french: "Tu es trop gentil avec elle.", english: "You are too nice to her.", audio: "171_Tu_es_trop_gentil_avec_elle..wav" },
  { french: "Il est plus studieux que nous.", english: "He is more studious than us.", audio: "172_Il_est_plus_studieux_que_nous..wav" },
  { french: "Elle est à Paris.", english: "She is in Paris.", audio: "173_Elle_est_à_Paris..wav" },
  { french: "Elles sont de Paris.", english: "They are from Paris.", audio: "174_Elles_sont_de_Paris..wav" },
  { french: "Nous sommes lundi.", english: "It is Monday.", audio: "175_Nous_sommes_lundi..wav" },
  { french: "On est lundi.", english: "It is Monday.", audio: "176_On_est_lundi..wav" },
  { french: "Il a deux chiens.", english: "He has two dogs.", audio: "177_Il_a_deux_chiens..wav" },
  { french: "Nous avons faim.", english: "We are hungry.", audio: "178_Nous_avons_faim..wav" },
  { french: "Vous avez du courage.", english: "You have courage.", audio: "179_Vous_avez_du_courage..wav" },
  { french: "Elles ont vingt ans.", english: "They are twenty years old.", audio: "180_Elles_ont_vingt_ans..wav" },
  { french: "Ça a l'air bon !", english: "That looks good!", audio: "181_Ça_a_l'air_bon.wav" },
  { french: "Ça va ?", english: "How are you?", audio: "182_Ça_va.wav" },
  { french: "C'est ça.", english: "That's it.", audio: "183_C'est_ça..wav" },
  { french: "Oui, je suis étudiant.", english: "Yes, I am a student.", audio: "184_Oui,_je_suis_étudiant..wav" },
  { french: "Non, je suis employé.", english: "No, I am an employee.", audio: "185_Non,_je_suis_employé..wav" },
  { french: "C'est du sel, ça ?", english: "Is that salt?", audio: "186_C'est_du_sel_ça.wav" },
  { french: "Oui, c'est du sel.", english: "Yes, it is salt.", audio: "187_Oui,_c'est_du_sel..wav" },
  { french: "Non, c'est du sucre.", english: "No, it is sugar.", audio: "188_Non,_c'est_du_sucre..wav" },
  { french: "Je parle français.", english: "I speak French.", audio: "189_Je_parle_français..wav" },
  { french: "Je parle anglais.", english: "I speak English.", audio: "190_Je_parle_anglais..wav" },
  { french: "Je parle japonais.", english: "I speak Japanese.", audio: "191_Je_parle_japonais..wav" },
  { french: "J'aime le cinéma.", english: "I like the cinema.", audio: "192_J'aime_le_cinéma..wav" },
  { french: "J'aime la musique.", english: "I like music.", audio: "193_J'aime_la_musique..wav" },
  { french: "J'aime les livres.", english: "I like books.", audio: "194_J'aime_les_livres..wav" },
  { french: "J'achète un CD.", english: "I am buying a CD.", audio: "195_J'achète_un_CD..wav" },
  { french: "J'appelle un taxi.", english: "I am calling a taxi.", audio: "196_J'appelle_un_taxi..wav" },
  { french: "Nous commençons.", english: "We are starting.", audio: "197_Nous_commençons..wav" },
  { french: "Ils sont grands.", english: "They are tall.", audio: "198_Ils_sont_grands..wav" },
  { french: "Elles sont grandes.", english: "They are tall.", audio: "199_Elles_sont_grandes..wav" },
  { french: "un sac rouge", english: "a red bag", audio: "200_un_sac_rouge.wav" },
  { french: "des sacs rouges", english: "red bags", audio: "201_des_sacs_rouges.wav" },
  { french: "une valise légère", english: "a light suitcase", audio: "202_une_valise_légère.wav" },
  { french: "des valises légères", english: "light suitcases", audio: "203_des_valises_légères.wav" },
  { french: "un beau musée", english: "a beautiful museum", audio: "204_un_beau_musée.wav" },
  { french: "un bel appartement", english: "a beautiful apartment", audio: "205_un_bel_appartement.wav" },
  { french: "une belle boutique", english: "a beautiful shop", audio: "206_une_belle_boutique.wav" },
  { french: "de beaux musées", english: "beautiful museums", audio: "207_de_beaux_musées.wav" },
  { french: "de beaux appartements", english: "beautiful apartments", audio: "208_de_beaux_appartements.wav" },
  { french: "de belles boutiques", english: "beautiful shops", audio: "209_de_belles_boutiques.wav" },
  { french: "un joli vase", english: "a pretty vase", audio: "210_un_joli_vase.wav" },
  { french: "de jolis vases", english: "pretty vases", audio: "211_de_jolis_vases.wav" },
  { french: "une autre question", english: "another question", audio: "212_une_autre_question.wav" },
  { french: "d'autres questions", english: "other questions", audio: "213_d'autres_questions.wav" },
  { french: "Il parle français.", english: "He speaks French.", audio: "214_Il_parle_français..wav" },
  { french: "Il ne parle pas français.", english: "He does not speak French.", audio: "215_Il_ne_parle_pas_français..wav" },
  { french: "Ce n'est pas mon stylo.", english: "It is not my pen.", audio: "216_Ce_n'est_pas_mon_stylo..wav" },
  { french: "J'ai une tablette.", english: "I have a tablet.", audio: "217_J'ai_une_tablette..wav" },
  { french: "Elle mange des légumes.", english: "She eats vegetables.", audio: "218_Elle_mange_des_légumes..wav" },
  { french: "Il fait du tennis.", english: "He plays tennis.", audio: "219_Il_fait_du_tennis..wav" },
  { french: "Il ne fait pas de tennis.", english: "He does not play tennis.", audio: "220_Il_ne_fait_pas_de_tennis..wav" },
  { french: "Il y a de l'eau.", english: "There is water.", audio: "221_Il_y_a_de_l'eau..wav" },
  { french: "C'est du lait.", english: "It is milk.", audio: "222_C'est_du_lait..wav" },
  { french: "Ce n'est pas du lait.", english: "It is not milk.", audio: "223_Ce_n'est_pas_du_lait..wav" },
  { french: "J'aime le lait.", english: "I like milk.", audio: "224_J'aime_le_lait..wav" },
  { french: "Tu parles français ?", english: "Do you speak French?", audio: "225_Tu_parles_français.wav" },
  { french: "Mark parle français ?", english: "Does Mark speak French?", audio: "226_Mark_parle_français.wav" },
  { french: "Est-ce que Mark parle français ?", english: "Does Mark speak French?", audio: "227_Est-ce_que_Mark_parle_français.wav" },
  { french: "Parles-tu français ?", english: "Do you speak French?", audio: "228_Parles-tu_français.wav" },
  { french: "Mark parle-t-il français ?", english: "Does Mark speak French?", audio: "229_Mark_parle-t-il_français.wav" },
  { french: "Aime-t-il le cinéma ?", english: "Does he like the cinema?", audio: "230_Aime-t-il_le_cinéma.wav" },
  { french: "Oui, j'ai faim.", english: "Yes, I am hungry.", audio: "231_Oui,_j'ai_faim..wav" },
  { french: "Non, je n'ai pas faim.", english: "No, I am not hungry.", audio: "232_Non,_je_n'ai_pas_faim..wav" },
  { french: "Ouvre la porte.", english: "Open the door.", audio: "233_Ouvre_la_porte..wav" },
  { french: "N'aie pas peur.", english: "Don't be afraid.", audio: "234_N'aie_pas_peur..wav" },
  { french: "Il a vingt et un ans.", english: "He is twenty-one years old.", audio: "235_Il_a_vingt_et_un_ans..wav" },
  { french: "Je suis musicien.", english: "I am a musician.", audio: "236_Je_suis_musicien..wav" },
  { french: "J'aime les films d'aventures.", english: "I like adventure movies.", audio: "237_J'aime_les_films_d'aventures..wav" },
  { french: "Soyez calmes.", english: "Be calm.", audio: "238_Soyez_calmes..wav" },
  { french: "Ce sont des violettes.", english: "These are violets.", audio: "239_Ce_sont_des_violettes..wav" },
  { french: "Quelle belle vue !", english: "What a beautiful view!", audio: "240_Quelle_belle_vue.wav" },
  { french: "Il est deux heures dix.", english: "It is two ten.", audio: "241_Il_est_deux_heures_dix..wav" },
  { french: "Il est deux heures et quart.", english: "It is a quarter past two.", audio: "242_Il_est_deux_heures_et_quart..wav" },
  { french: "Il est deux heures et demie.", english: "It is half past two.", audio: "243_Il_est_deux_heures_et_demie..wav" },
  { french: "Il est trois heures moins le quart.", english: "It is a quarter to three.", audio: "244_Il_est_trois_heures_moins_le_quart..wav" },
  { french: "Il est minuit.", english: "It is midnight.", audio: "245_Il_est_minuit..wav" },
  { french: "Il est midi.", english: "It is noon.", audio: "246_Il_est_midi..wav" },
  { french: "Il fait mauvais.", english: "It is bad weather.", audio: "247_Il_fait_mauvais..wav" },
  { french: "Il fait doux.", english: "It is mild.", audio: "248_Il_fait_doux..wav" },
  { french: "Il fait froid.", english: "It is cold.", audio: "249_Il_fait_froid..wav" },
  { french: "Il fait frais.", english: "It is cool.", audio: "250_Il_fait_frais..wav" },
  { french: "Il y a des nuages.", english: "It is cloudy.", audio: "251_Il_y_a_des_nuages..wav" },
  { french: "Il pleut.", english: "It is raining.", audio: "252_Il_pleut..wav" },
  { french: "Il y a beaucoup de musées à Paris.", english: "There are many museums in Paris.", audio: "253_Il_y_a_beaucoup_de_musées_à_Paris..wav" },
  { french: "Il arrive souvent des catastrophes naturelles dans ce pays.", english: "Natural disasters often happen in this country.", audio: "254_Il_arrive_souvent_des_catastrophes_natur.wav" },
  { french: "Il faut prononcer clairement.", english: "You must pronounce clearly.", audio: "255_Il_faut_prononcer_clairement..wav" },
  { french: "Il ne faut pas fumer ici.", english: "You must not smoke here.", audio: "256_Il_ne_faut_pas_fumer_ici..wav" },
  { french: "Il faut de la viande pour faire cette recette.", english: "You need meat to make this recipe.", audio: "257_Il_faut_de_la_viande_pour_faire_cette_re.wav" },
  { french: "Il paraît qu'elle va partir en France pour étudier.", english: "It seems she is going to France to study.", audio: "258_Il_paraît_qu'elle_va_partir_en_France_po.wav" },
  { french: "Il est difficile d'apprendre plusieurs langues en même temps.", english: "It is difficult to learn several languages at the same time.", audio: "259_Il_est_difficile_d'apprendre_plusieurs_l.wav" },
  { french: "C'est difficile d'apprendre plusieurs langues en même temps.", english: "It is difficult to learn several languages at the same time.", audio: "260_C'est_difficile_d'apprendre_plusieurs_la.wav" },
  { french: "un vélo", english: "a bicycle", audio: "261_un_vélo.wav" },
  { french: "des vélos", english: "bicycles", audio: "262_des_vélos.wav" },
  { french: "une voiture", english: "a car", audio: "263_une_voiture.wav" },
  { french: "des voitures", english: "cars", audio: "264_des_voitures.wav" },
  { french: "le père de Paul", english: "Paul's father", audio: "265_le_père_de_Paul.wav" },
  { french: "la Terre", english: "the Earth", audio: "266_la_Terre.wav" },
  { french: "les États-Unis", english: "the United States", audio: "267_les_États-Unis.wav" },
  { french: "le vin", english: "wine", audio: "268_le_vin.wav" },
  { french: "l'amour", english: "love", audio: "269_l'amour.wav" },
  { french: "les fruits", english: "fruits", audio: "270_les_fruits.wav" },
  { french: "du vin", english: "wine", audio: "271_du_vin.wav" },
  { french: "de la bière", english: "beer", audio: "272_de_la_bière.wav" },
  { french: "de l'argent", english: "money", audio: "273_de_l'argent.wav" },
  { french: "de l'eau", english: "water", audio: "274_de_l'eau.wav" },
  { french: "un ami", english: "a friend", audio: "275_un_ami.wav" },
  { french: "des hôtels", english: "hotels", audio: "276_des_hôtels.wav" },
  { french: "une amie", english: "a friend", audio: "277_une_amie.wav" },
  { french: "les étudiants", english: "students", audio: "278_les_étudiants.wav" },
  { french: "Voici un stylo.", english: "Here is a pen.", audio: "279_Voici_un_stylo..wav" },
  { french: "Voici des stylos.", english: "Here are pens.", audio: "280_Voici_des_stylos..wav" },
  { french: "Voilà une feuille.", english: "There is a sheet.", audio: "281_Voilà_une_feuille..wav" },
  { french: "Voilà des feuilles.", english: "There are sheets.", audio: "282_Voilà_des_feuilles..wav" },
  { french: "Voici Paul.", english: "Here is Paul.", audio: "283_Voici_Paul..wav" },
  { french: "Voilà le Louvre.", english: "There is the Louvre.", audio: "284_Voilà_le_Louvre..wav" },
  { french: "C'est un restaurant.", english: "It is a restaurant.", audio: "285_C'est_un_restaurant..wav" },
  { french: "C'est de l'eau.", english: "It is water.", audio: "286_C'est_de_l'eau..wav" },
  { french: "Ce sont des restaurants.", english: "These are restaurants.", audio: "287_Ce_sont_des_restaurants..wav" },
  { french: "Il y a un livre sur la table.", english: "There is a book on the table.", audio: "288_Il_y_a_un_livre_sur_la_table..wav" },
  { french: "Il y a des livres sur la table.", english: "There are books on the table.", audio: "289_Il_y_a_des_livres_sur_la_table..wav" },
  { french: "Je vais chercher Marie à l'aéroport.", english: "I am going to pick up Marie at the airport.", audio: "290_Je_vais_chercher_Marie_à_l'aéroport..wav" },
  { french: "Je viens souvent ici prendre un café.", english: "I often come here to have a coffee.", audio: "291_Je_viens_souvent_ici_prendre_un_café..wav" },
  { french: "C'est au bout de cette rue.", english: "It is at the end of this street.", audio: "292_C'est_au_bout_de_cette_rue..wav" },
  { french: "C'est en face du cinéma.", english: "It is opposite the cinema.", audio: "293_C'est_en_face_du_cinéma..wav" },
  { french: "C'est loin des Champs-Élysées.", english: "It is far from the Champs-Élysées.", audio: "294_C'est_loin_des_Champs-Élysées..wav" },
  { french: "à la mer", english: "to the sea", audio: "295_à_la_mer.wav" },
  { french: "à l'école", english: "to school", audio: "296_à_l'école.wav" },
  { french: "de la gare", english: "from the train station", audio: "297_de_la_gare.wav" },
  { french: "de l'hôpital", english: "from the hospital", audio: "298_de_l'hôpital.wav" },
  { french: "Parce que j'ai de la fièvre.", english: "Because I have a fever.", audio: "299_Parce_que_j'ai_de_la_fièvre..wav" },
  { french: "C'est quand, ton anniversaire ?", english: "When is your birthday?", audio: "300_C'est_quand_ton_anniversaire.wav" },
  { french: "Elle est comment, son amie ?", english: "What is her friend like?", audio: "301_Elle_est_comment_son_amie.wav" },
  { french: "Pourquoi tu ne sors pas ?", english: "Why don't you go out?", audio: "302_Pourquoi_tu_ne_sors_pas.wav" },
  { french: "C'est combien, ce livre ?", english: "How much is this book?", audio: "303_C'est_combien_ce_livre.wav" },
  { french: "Tu as combien de cours demain ?", english: "How many classes do you have tomorrow?", audio: "304_Tu_as_combien_de_cours_demain.wav" }
];
