import { PlaybackConfig, SpeedMode, SentenceItem } from './types';

export const MODE_CONFIGS: Record<SpeedMode, PlaybackConfig> = {
  [SpeedMode.FAST]: { rate: 1.2, postDelayMs: 500 },
  [SpeedMode.NORMAL]: { rate: 1.0, postDelayMs: 1200 },
  [SpeedMode.SLOW]: { rate: 0.8, postDelayMs: 2000 },
};

export const SENTENCE_DATA: SentenceItem[] = [
  { french: "Je suis japonais.", english: "I am Japanese.", audio: "001_Je_suis_japonais..mp3" },
  { french: "Je suis anglais.", english: "I am English.", audio: "002_Je_suis_anglais..mp3" },
  { french: "Tu es français ?", english: "Are you French?", audio: "003_Tu_es_français.mp3" },
  { french: "Tu es étudiant ?", english: "Are you a student?", audio: "004_Tu_es_étudiant.mp3" },
  { french: "Il est grand.", english: "He is tall.", audio: "005_Il_est_grand..mp3" },
  { french: "Elle est grande.", english: "She is tall.", audio: "006_Elle_est_grande..mp3" },
  { french: "Paul et Marie sont étudiants.", english: "Paul and Marie are students.", audio: "007_Paul_et_Marie_sont_étudiants..mp3" },
  { french: "Ils sont des étudiants.", english: "They are students.", audio: "008_Ils_sont_des_étudiants..mp3" },
  { french: "Elles sont heureuses.", english: "They are happy.", audio: "009_Elles_sont_heureuses..mp3" },
  { french: "Vous êtes bien ?", english: "Are you comfortable?", audio: "010_Vous_êtes_bien.mp3" },
  { french: "J'ai une voiture.", english: "I have a car.", audio: "011_J'ai_une_voiture..mp3" },
  { french: "Tu as quel âge ?", english: "How old are you?", audio: "012_Tu_as_quel_âge.mp3" },
  { french: "Elle a beaucoup de livres.", english: "She has a lot of books.", audio: "013_Elle_a_beaucoup_de_livres..mp3" },
  { french: "Ils ont un chat.", english: "They have a cat.", audio: "014_Ils_ont_un_chat..mp3" },
  { french: "On a faim.", english: "We are hungry.", audio: "015_On_a_faim..mp3" },
  { french: "On a un chien.", english: "We have a dog.", audio: "016_On_a_un_chien..mp3" },
  { french: "Nous parlons le français.", english: "We speak French.", audio: "017_Nous_parlons_le_français..mp3" },
  { french: "Nous étudions le français.", english: "We study French.", audio: "018_Nous_étudions_le_français..mp3" },
  { french: "Nous mangeons.", english: "We are eating.", audio: "019_Nous_mangeons..mp3" },
  { french: "Tu aimes le chocolat ?", english: "Do you like chocolate?", audio: "020_Tu_aimes_le_chocolat.mp3" },
  { french: "Elles aiment la musique.", english: "They like music.", audio: "021_Elles_aiment_la_musique..mp3" },
  { french: "Il ne parle pas anglais.", english: "He does not speak English.", audio: "022_Il_ne_parle_pas_anglais..mp3" },
  { french: "Il finit son travail.", english: "He finishes his work.", audio: "023_Il_finit_son_travail..mp3" },
  { french: "Nous finissons le travail.", english: "We finish the work.", audio: "024_Nous_finissons_le_travail..mp3" },
  { french: "Tu finis tes devoirs ?", english: "Are you finishing your homework?", audio: "025_Tu_finis_tes_devoirs.mp3" },
  { french: "Nous choisissons ce film.", english: "We choose this movie.", audio: "026_Nous_choisissons_ce_film..mp3" },
  { french: "Je vais à Paris.", english: "I am going to Paris.", audio: "027_Je_vais_à_Paris..mp3" },
  { french: "Je vais au Canada.", english: "I am going to Canada.", audio: "028_Je_vais_au_Canada..mp3" },
  { french: "Je vais au Brésil.", english: "I am going to Brazil.", audio: "029_Je_vais_au_Brésil..mp3" },
  { french: "Je vais en France.", english: "I am going to France.", audio: "030_Je_vais_en_France..mp3" },
  { french: "Je vais aux États-Unis.", english: "I am going to the United States.", audio: "031_Je_vais_aux_États-Unis..mp3" },
  { french: "Je vais aux toilettes.", english: "I am going to the restroom.", audio: "032_Je_vais_aux_toilettes..mp3" },
  { french: "Nous allons au musée.", english: "We are going to the museum.", audio: "033_Nous_allons_au_musée..mp3" },
  { french: "Nous allons à la gare.", english: "We are going to the train station.", audio: "034_Nous_allons_à_la_gare..mp3" },
  { french: "Vous allez où ?", english: "Where are you going?", audio: "035_Vous_allez_où.mp3" },
  { french: "Ils vont au Canada.", english: "They are going to Canada.", audio: "036_Ils_vont_au_Canada..mp3" },
  { french: "On va au cinéma.", english: "We are going to the movies.", audio: "037_On_va_au_cinéma..mp3" },
  { french: "On va bien.", english: "We are doing well.", audio: "038_On_va_bien..mp3" },
  { french: "Je viens de Tokyo.", english: "I come from Tokyo.", audio: "039_Je_viens_de_Tokyo..mp3" },
  { french: "Je viens de France.", english: "I come from France.", audio: "040_Je_viens_de_France..mp3" },
  { french: "Je viens du Japon.", english: "I come from Japan.", audio: "041_Je_viens_du_Japon..mp3" },
  { french: "Je viens du Canada.", english: "I come from Canada.", audio: "042_Je_viens_du_Canada..mp3" },
  { french: "Je viens du Brésil.", english: "I come from Brazil.", audio: "043_Je_viens_du_Brésil..mp3" },
  { french: "Je viens du Chili.", english: "I come from Chile.", audio: "044_Je_viens_du_Chili..mp3" },
  { french: "Je viens des États-Unis.", english: "I come from the United States.", audio: "045_Je_viens_des_États-Unis..mp3" },
  { french: "Ils viennent de France.", english: "They come from France.", audio: "046_Ils_viennent_de_France..mp3" },
  { french: "Ils viennent des États-Unis.", english: "They come from the United States.", audio: "047_Ils_viennent_des_États-Unis..mp3" },
  { french: "Vous venez du Japon ?", english: "Do you come from Japan?", audio: "048_Vous_venez_du_Japon.mp3" },
  { french: "La chemise est blanche.", english: "The shirt is white.", audio: "049_La_chemise_est_blanche..mp3" },
  { french: "Les maisons sont grandes.", english: "The houses are big.", audio: "050_Les_maisons_sont_grandes..mp3" },
  { french: "Les fleurs sont rouges.", english: "The flowers are red.", audio: "051_Les_fleurs_sont_rouges..mp3" },
  { french: "Ils sont contents.", english: "They are happy.", audio: "052_Ils_sont_contents..mp3" },
  { french: "C'est un bel appartement.", english: "It's a beautiful apartment.", audio: "053_C'est_un_bel_appartement..mp3" },
  { french: "Ce sont de beaux jardins.", english: "These are beautiful gardens.", audio: "054_Ce_sont_de_beaux_jardins..mp3" },
  { french: "C'est mon école.", english: "It's my school.", audio: "055_C'est_mon_école..mp3" },
  { french: "C'est mon amie.", english: "She is my friend.", audio: "056_C'est_mon_amie..mp3" },
  { french: "C'est ton amie ?", english: "Is she your friend?", audio: "057_C'est_ton_amie.mp3" },
  { french: "C'est son histoire.", english: "It's his story.", audio: "058_C'est_son_histoire..mp3" },
  { french: "C'est mon père.", english: "He is my father.", audio: "059_C'est_mon_père..mp3" },
  { french: "C'est mon stylo.", english: "It's my pen.", audio: "060_C'est_mon_stylo..mp3" },
  { french: "Ce sont mes voitures.", english: "These are my cars.", audio: "061_Ce_sont_mes_voitures..mp3" },
  { french: "Regardez cet arbre.", english: "Look at this tree.", audio: "062_Regardez_cet_arbre..mp3" },
  { french: "C'est cet hôtel.", english: "It's this hotel.", audio: "063_C'est_cet_hôtel..mp3" },
  { french: "Ce sont ces photos.", english: "These are those photos.", audio: "064_Ce_sont_ces_photos..mp3" },
  { french: "C'est ce livre ?", english: "Is it this book?", audio: "065_C'est_ce_livre.mp3" },
  { french: "Je n'ai pas de tablette.", english: "I don't have a tablet.", audio: "066_Je_n'ai_pas_de_tablette..mp3" },
  { french: "Je n'ai pas de stylo.", english: "I don't have a pen.", audio: "067_Je_n'ai_pas_de_stylo..mp3" },
  { french: "Je n'ai pas d'argent.", english: "I don't have money.", audio: "068_Je_n'ai_pas_d'argent..mp3" },
  { french: "Je n'ai pas d'amis.", english: "I don't have friends.", audio: "069_Je_n'ai_pas_d'amis..mp3" },
  { french: "Il n'y a pas d'eau.", english: "There is no water.", audio: "070_Il_n'y_a_pas_d'eau..mp3" },
  { french: "Il n'y a pas de lait.", english: "There is no milk.", audio: "071_Il_n'y_a_pas_de_lait..mp3" },
  { french: "Il n'y a pas de problème.", english: "There is no problem.", audio: "072_Il_n'y_a_pas_de_problème..mp3" },
  { french: "Nous n'avons pas d'idée.", english: "We have no idea.", audio: "073_Nous_n'avons_pas_d'idée..mp3" },
  { french: "Elle ne mange pas de légumes.", english: "She doesn't eat vegetables.", audio: "074_Elle_ne_mange_pas_de_légumes..mp3" },
  { french: "Tu ne manges pas d'ananas.", english: "You don't eat pineapples.", audio: "075_Tu_ne_manges_pas_d'ananas..mp3" },
  { french: "Il ne boit pas d'alcool.", english: "He doesn't drink alcohol.", audio: "076_Il_ne_boit_pas_d'alcool..mp3" },
  { french: "Il n'achète pas d'ordinateur.", english: "He isn't buying a computer.", audio: "077_Il_n'achète_pas_d'ordinateur..mp3" },
  { french: "Elle n'a pas d'enfants.", english: "She has no children.", audio: "078_Elle_n'a_pas_d'enfants..mp3" },
  { french: "Je n'aime pas le lait.", english: "I don't like milk.", audio: "079_Je_n'aime_pas_le_lait..mp3" },
  { french: "Il n'est plus jeune.", english: "He is no longer young.", audio: "080_Il_n'est_plus_jeune..mp3" },
  { french: "Elle ne mange jamais de nattô.", english: "She never eats natto.", audio: "081_Elle_ne_mange_jamais_de_nattô..mp3" },
  { french: "Ce n'est pas un problème.", english: "It's not a problem.", audio: "082_Ce_n'est_pas_un_problème..mp3" },
  { french: "Ce n'est pas un stylo.", english: "It's not a pen.", audio: "083_Ce_n'est_pas_un_stylo..mp3" },
  { french: "Ce n'est pas un hôtel.", english: "It's not a hotel.", audio: "084_Ce_n'est_pas_un_hôtel..mp3" },
  { french: "Ce n'est pas une école.", english: "It's not a school.", audio: "085_Ce_n'est_pas_une_école..mp3" },
  { french: "Ce n'est pas une voiture.", english: "It's not a car.", audio: "086_Ce_n'est_pas_une_voiture..mp3" },
  { french: "Ce ne sont pas des étudiants.", english: "They are not students.", audio: "087_Ce_ne_sont_pas_des_étudiants..mp3" },
  { french: "Ce ne sont pas des livres.", english: "These are not books.", audio: "088_Ce_ne_sont_pas_des_livres..mp3" },
  { french: "Ce ne sont pas des voitures japonaises.", english: "These are not Japanese cars.", audio: "089_Ce_ne_sont_pas_des_voitures_japonaises..mp3" },
  { french: "Ce ne sont pas des touristes.", english: "They are not tourists.", audio: "090_Ce_ne_sont_pas_des_touristes..mp3" },
  { french: "Je vais sortir.", english: "I am going to go out.", audio: "091_Je_vais_sortir..mp3" },
  { french: "Je vais manger.", english: "I am going to eat.", audio: "092_Je_vais_manger..mp3" },
  { french: "Je vais visiter Paris.", english: "I am going to visit Paris.", audio: "093_Je_vais_visiter_Paris..mp3" },
  { french: "Tu vas partir ce soir ?", english: "Are you leaving tonight?", audio: "094_Tu_vas_partir_ce_soir.mp3" },
  { french: "Il va manger le déjeuner.", english: "He is going to eat lunch.", audio: "095_Il_va_manger_le_déjeuner..mp3" },
  { french: "Il va prendre un café.", english: "He is going to have a coffee.", audio: "096_Il_va_prendre_un_café..mp3" },
  { french: "Elle va prendre le train.", english: "She is going to take the train.", audio: "097_Elle_va_prendre_le_train..mp3" },
  { french: "Elle va prendre le bus.", english: "She is going to take the bus.", audio: "098_Elle_va_prendre_le_bus..mp3" },
  { french: "Nous allons acheter une voiture.", english: "We are going to buy a car.", audio: "099_Nous_allons_acheter_une_voiture..mp3" },
  { french: "Nous allons étudier le français.", english: "We are going to study French.", audio: "100_Nous_allons_étudier_le_français..mp3" },
  { french: "Vous allez comprendre.", english: "You are going to understand.", audio: "101_Vous_allez_comprendre..mp3" },
  { french: "Vous allez écouter la radio.", english: "You are going to listen to the radio.", audio: "102_Vous_allez_écouter_la_radio..mp3" },
  { french: "Vous allez partir ?", english: "Are you going to leave?", audio: "103_Vous_allez_partir.mp3" },
  { french: "Ils vont arriver bientôt.", english: "They are going to arrive soon.", audio: "104_Ils_vont_arriver_bientôt..mp3" },
  { french: "On va partir bientôt.", english: "We are going to leave soon.", audio: "105_On_va_partir_bientôt..mp3" },
  { french: "On va manger ce soir.", english: "We are going to eat tonight.", audio: "106_On_va_manger_ce_soir..mp3" },
  { french: "On va sortir.", english: "We are going to go out.", audio: "107_On_va_sortir..mp3" },
  { french: "Nous venons d'arriver à Bordeaux.", english: "We just arrived in Bordeaux.", audio: "108_Nous_venons_d'arriver_à_Bordeaux..mp3" },
  { french: "Nous venons de manger.", english: "We just ate.", audio: "109_Nous_venons_de_manger..mp3" },
  { french: "Nous venons de partir.", english: "We just left.", audio: "110_Nous_venons_de_partir..mp3" },
  { french: "Quel âge a-t-il ?", english: "How old is he?", audio: "111_Quel_âge_a-t-il.mp3" },
  { french: "Quel temps fait-il ?", english: "What is the weather like?", audio: "112_Quel_temps_fait-il.mp3" },
  { french: "Quel est votre nom ?", english: "What is your name?", audio: "113_Quel_est_votre_nom.mp3" },
  { french: "Quelle est votre profession ?", english: "What is your profession?", audio: "114_Quelle_est_votre_profession.mp3" },
  { french: "Quelle est votre nationalité ?", english: "What is your nationality?", audio: "115_Quelle_est_votre_nationalité.mp3" },
  { french: "Quelle heure est-il ?", english: "What time is it?", audio: "116_Quelle_heure_est-il.mp3" },
  { french: "Quelles fleurs sont sur la table ?", english: "Which flowers are on the table?", audio: "117_Quelles_fleurs_sont_sur_la_table.mp3" },
  { french: "Combien coûte ce livre ?", english: "How much does this book cost?", audio: "118_Combien_coûte_ce_livre.mp3" },
  { french: "Où habitez-vous ?", english: "Where do you live?", audio: "119_Où_habitez-vous.mp3" },
  { french: "Quand partez-vous ?", english: "When are you leaving?", audio: "120_Quand_partez-vous.mp3" },
  { french: "Est-ce que tu parles français ?", english: "Do you speak French?", audio: "121_Est-ce_que_tu_parles_français.mp3" },
  { french: "Voyage-t-il au Japon ?", english: "Is he traveling to Japan?", audio: "122_Voyage-t-il_au_Japon.mp3" },
  { french: "Va à l'école.", english: "Go to school.", audio: "123_Va_à_l'école..mp3" },
  { french: "Parle un peu.", english: "Speak a little.", audio: "124_Parle_un_peu..mp3" },
  { french: "Parle français !", english: "Speak French!", audio: "125_Parle_français.mp3" },
  { french: "Regarde cette fleur !", english: "Look at this flower!", audio: "126_Regarde_cette_fleur.mp3" },
  { french: "Regardez ces photos.", english: "Look at these photos.", audio: "127_Regardez_ces_photos..mp3" },
  { french: "Regardez cette photo.", english: "Look at this photo.", audio: "128_Regardez_cette_photo..mp3" },
  { french: "Soyez calmes !", english: "Be calm!", audio: "129_Soyez_calmes.mp3" },
  { french: "Allons au cinéma !", english: "Let's go to the movies!", audio: "130_Allons_au_cinéma.mp3" },
  { french: "Allons au restaurant !", english: "Let's go to the restaurant!", audio: "131_Allons_au_restaurant.mp3" },
  { french: "Écoutons la musique !", english: "Let's listen to music!", audio: "132_Écoutons_la_musique.mp3" },
  { french: "C'est très bon.", english: "It's very good.", audio: "133_C'est_très_bon..mp3" },
  { french: "C'est un hôtel.", english: "It's a hotel.", audio: "134_C'est_un_hôtel..mp3" },
  { french: "Ce sont des stylos.", english: "These are pens.", audio: "135_Ce_sont_des_stylos..mp3" },
  { french: "Il est dix heures.", english: "It is ten o'clock.", audio: "136_Il_est_dix_heures..mp3" },
  { french: "Il fait beau.", english: "The weather is nice.", audio: "137_Il_fait_beau..mp3" },
  { french: "Il fait chaud.", english: "It is hot.", audio: "138_Il_fait_chaud..mp3" },
  { french: "Il y a du vent.", english: "It is windy.", audio: "139_Il_y_a_du_vent..mp3" },
  { french: "Il neige.", english: "It is snowing.", audio: "140_Il_neige..mp3" },
  { french: "Il est plus grand que moi.", english: "He is taller than me.", audio: "141_Il_est_plus_grand_que_moi..mp3" },
  { french: "Je vais au cinéma avec lui.", english: "I am going to the movies with him.", audio: "142_Je_vais_au_cinéma_avec_lui..mp3" },
  { french: "Si, j'ai faim.", english: "Yes, I am hungry.", audio: "143_Si,_j'ai_faim..mp3" },
  { french: "Je parle aux étudiants.", english: "I am talking to the students.", audio: "144_Je_parle_aux_étudiants..mp3" },
  { french: "C'est la voiture du père.", english: "It's the father's car.", audio: "145_C'est_la_voiture_du_père..mp3" },
  { french: "C'est le frère de Paul.", english: "It's Paul's brother.", audio: "146_C'est_le_frère_de_Paul..mp3" },
  { french: "Je rentre du bureau.", english: "I am coming back from the office.", audio: "147_Je_rentre_du_bureau..mp3" },
  { french: "C'est un vin du Chili.", english: "It's a wine from Chile.", audio: "148_C'est_un_vin_du_Chili..mp3" },
  { french: "Je finis mon travail à cinq heures.", english: "I finish my work at five o'clock.", audio: "149_Je_finis_mon_travail_à_cinq_heures..mp3" },
  { french: "Mon frère grandit de jour en jour.", english: "My brother is growing day by day.", audio: "150_Mon_frère_grandit_de_jour_en_jour..mp3" },
  { french: "ce jardin", english: "this garden", audio: "151_ce_jardin.mp3" },
  { french: "cet arbre", english: "this tree", audio: "152_cet_arbre.mp3" },
  { french: "cette fleur", english: "this flower", audio: "153_cette_fleur.mp3" },
  { french: "ces jardins", english: "these gardens", audio: "154_ces_jardins.mp3" },
  { french: "ces arbres", english: "these trees", audio: "155_ces_arbres.mp3" },
  { french: "ces fleurs", english: "these flowers", audio: "156_ces_fleurs.mp3" },
  { french: "cet hôtel", english: "this hotel", audio: "157_cet_hôtel.mp3" },
  { french: "ce livre-ci", english: "this book", audio: "158_ce_livre-ci.mp3" },
  { french: "ce livre-là", english: "that book", audio: "159_ce_livre-là.mp3" },
  { french: "mon père", english: "my father", audio: "160_mon_père.mp3" },
  { french: "ta mère", english: "your mother", audio: "161_ta_mère.mp3" },
  { french: "ses parents", english: "his/her parents", audio: "162_ses_parents.mp3" },
  { french: "mon amie", english: "my friend", audio: "163_mon_amie.mp3" },
  { french: "ton école", english: "your school", audio: "164_ton_école.mp3" },
  { french: "son histoire", english: "his/her story", audio: "165_son_histoire.mp3" },
  { french: "Je suis français.", english: "I am French.", audio: "166_Je_suis_français..mp3" },
  { french: "Et toi ?", english: "And you?", audio: "167_Et_toi.mp3" },
  { french: "Moi aussi.", english: "Me too.", audio: "168_Moi_aussi..mp3" },
  { french: "C'est Théo ?", english: "Is that Théo?", audio: "169_C'est_Théo.mp3" },
  { french: "Oui, c'est lui.", english: "Yes, it is him.", audio: "170_Oui,_c'est_lui..mp3" },
  { french: "Tu es trop gentil avec elle.", english: "You are too nice to her.", audio: "171_Tu_es_trop_gentil_avec_elle..mp3" },
  { french: "Il est plus studieux que nous.", english: "He is more studious than us.", audio: "172_Il_est_plus_studieux_que_nous..mp3" },
  { french: "Elle est à Paris.", english: "She is in Paris.", audio: "173_Elle_est_à_Paris..mp3" },
  { french: "Elles sont de Paris.", english: "They are from Paris.", audio: "174_Elles_sont_de_Paris..mp3" },
  { french: "Nous sommes lundi.", english: "It is Monday.", audio: "175_Nous_sommes_lundi..mp3" },
  { french: "On est lundi.", english: "It is Monday.", audio: "176_On_est_lundi..mp3" },
  { french: "Il a deux chiens.", english: "He has two dogs.", audio: "177_Il_a_deux_chiens..mp3" },
  { french: "Nous avons faim.", english: "We are hungry.", audio: "178_Nous_avons_faim..mp3" },
  { french: "Vous avez du courage.", english: "You have courage.", audio: "179_Vous_avez_du_courage..mp3" },
  { french: "Elles ont vingt ans.", english: "They are twenty years old.", audio: "180_Elles_ont_vingt_ans..mp3" },
  { french: "Ça a l'air bon !", english: "That looks good!", audio: "181_Ça_a_l'air_bon.mp3" },
  { french: "Ça va ?", english: "How are you?", audio: "182_Ça_va.mp3" },
  { french: "C'est ça.", english: "That's it.", audio: "183_C'est_ça..mp3" },
  { french: "Oui, je suis étudiant.", english: "Yes, I am a student.", audio: "184_Oui,_je_suis_étudiant..mp3" },
  { french: "Non, je suis employé.", english: "No, I am an employee.", audio: "185_Non,_je_suis_employé..mp3" },
  { french: "C'est du sel, ça ?", english: "Is that salt?", audio: "186_C'est_du_sel_ça.mp3" },
  { french: "Oui, c'est du sel.", english: "Yes, it is salt.", audio: "187_Oui,_c'est_du_sel..mp3" },
  { french: "Non, c'est du sucre.", english: "No, it is sugar.", audio: "188_Non,_c'est_du_sucre..mp3" },
  { french: "Je parle français.", english: "I speak French.", audio: "189_Je_parle_français..mp3" },
  { french: "Je parle anglais.", english: "I speak English.", audio: "190_Je_parle_anglais..mp3" },
  { french: "Je parle japonais.", english: "I speak Japanese.", audio: "191_Je_parle_japonais..mp3" },
  { french: "J'aime le cinéma.", english: "I like the cinema.", audio: "192_J'aime_le_cinéma..mp3" },
  { french: "J'aime la musique.", english: "I like music.", audio: "193_J'aime_la_musique..mp3" },
  { french: "J'aime les livres.", english: "I like books.", audio: "194_J'aime_les_livres..mp3" },
  { french: "J'achète un CD.", english: "I am buying a CD.", audio: "195_J'achète_un_CD..mp3" },
  { french: "J'appelle un taxi.", english: "I am calling a taxi.", audio: "196_J'appelle_un_taxi..mp3" },
  { french: "Nous commençons.", english: "We are starting.", audio: "197_Nous_commençons..mp3" },
  { french: "Ils sont grands.", english: "They are tall.", audio: "198_Ils_sont_grands..mp3" },
  { french: "Elles sont grandes.", english: "They are tall.", audio: "199_Elles_sont_grandes..mp3" },
  { french: "un sac rouge", english: "a red bag", audio: "200_un_sac_rouge.mp3" },
  { french: "des sacs rouges", english: "red bags", audio: "201_des_sacs_rouges.mp3" },
  { french: "une valise légère", english: "a light suitcase", audio: "202_une_valise_légère.mp3" },
  { french: "des valises légères", english: "light suitcases", audio: "203_des_valises_légères.mp3" },
  { french: "un beau musée", english: "a beautiful museum", audio: "204_un_beau_musée.mp3" },
  { french: "un bel appartement", english: "a beautiful apartment", audio: "205_un_bel_appartement.mp3" },
  { french: "une belle boutique", english: "a beautiful shop", audio: "206_une_belle_boutique.mp3" },
  { french: "de beaux musées", english: "beautiful museums", audio: "207_de_beaux_musées.mp3" },
  { french: "de beaux appartements", english: "beautiful apartments", audio: "208_de_beaux_appartements.mp3" },
  { french: "de belles boutiques", english: "beautiful shops", audio: "209_de_belles_boutiques.mp3" },
  { french: "un joli vase", english: "a pretty vase", audio: "210_un_joli_vase.mp3" },
  { french: "de jolis vases", english: "pretty vases", audio: "211_de_jolis_vases.mp3" },
  { french: "une autre question", english: "another question", audio: "212_une_autre_question.mp3" },
  { french: "d'autres questions", english: "other questions", audio: "213_d'autres_questions.mp3" },
  { french: "Il parle français.", english: "He speaks French.", audio: "214_Il_parle_français..mp3" },
  { french: "Il ne parle pas français.", english: "He does not speak French.", audio: "215_Il_ne_parle_pas_français..mp3" },
  { french: "Ce n'est pas mon stylo.", english: "It is not my pen.", audio: "216_Ce_n'est_pas_mon_stylo..mp3" },
  { french: "J'ai une tablette.", english: "I have a tablet.", audio: "217_J'ai_une_tablette..mp3" },
  { french: "Elle mange des légumes.", english: "She eats vegetables.", audio: "218_Elle_mange_des_légumes..mp3" },
  { french: "Il fait du tennis.", english: "He plays tennis.", audio: "219_Il_fait_du_tennis..mp3" },
  { french: "Il ne fait pas de tennis.", english: "He does not play tennis.", audio: "220_Il_ne_fait_pas_de_tennis..mp3" },
  { french: "Il y a de l'eau.", english: "There is water.", audio: "221_Il_y_a_de_l'eau..mp3" },
  { french: "C'est du lait.", english: "It is milk.", audio: "222_C'est_du_lait..mp3" },
  { french: "Ce n'est pas du lait.", english: "It is not milk.", audio: "223_Ce_n'est_pas_du_lait..mp3" },
  { french: "J'aime le lait.", english: "I like milk.", audio: "224_J'aime_le_lait..mp3" },
  { french: "Tu parles français ?", english: "Do you speak French?", audio: "225_Tu_parles_français.mp3" },
  { french: "Mark parle français ?", english: "Does Mark speak French?", audio: "226_Mark_parle_français.mp3" },
  { french: "Est-ce que Mark parle français ?", english: "Does Mark speak French?", audio: "227_Est-ce_que_Mark_parle_français.mp3" },
  { french: "Parles-tu français ?", english: "Do you speak French?", audio: "228_Parles-tu_français.mp3" },
  { french: "Mark parle-t-il français ?", english: "Does Mark speak French?", audio: "229_Mark_parle-t-il_français.mp3" },
  { french: "Aime-t-il le cinéma ?", english: "Does he like the cinema?", audio: "230_Aime-t-il_le_cinéma.mp3" },
  { french: "Oui, j'ai faim.", english: "Yes, I am hungry.", audio: "231_Oui,_j'ai_faim..mp3" },
  { french: "Non, je n'ai pas faim.", english: "No, I am not hungry.", audio: "232_Non,_je_n'ai_pas_faim..mp3" },
  { french: "Ouvre la porte.", english: "Open the door.", audio: "233_Ouvre_la_porte..mp3" },
  { french: "N'aie pas peur.", english: "Don't be afraid.", audio: "234_N'aie_pas_peur..mp3" },
  { french: "Il a vingt et un ans.", english: "He is twenty-one years old.", audio: "235_Il_a_vingt_et_un_ans..mp3" },
  { french: "Je suis musicien.", english: "I am a musician.", audio: "236_Je_suis_musicien..mp3" },
  { french: "J'aime les films d'aventures.", english: "I like adventure movies.", audio: "237_J'aime_les_films_d'aventures..mp3" },
  { french: "Soyez calmes.", english: "Be calm.", audio: "238_Soyez_calmes..mp3" },
  { french: "Ce sont des violettes.", english: "These are violets.", audio: "239_Ce_sont_des_violettes..mp3" },
  { french: "Quelle belle vue !", english: "What a beautiful view!", audio: "240_Quelle_belle_vue.mp3" },
  { french: "Il est deux heures dix.", english: "It is two ten.", audio: "241_Il_est_deux_heures_dix..mp3" },
  { french: "Il est deux heures et quart.", english: "It is a quarter past two.", audio: "242_Il_est_deux_heures_et_quart..mp3" },
  { french: "Il est deux heures et demie.", english: "It is half past two.", audio: "243_Il_est_deux_heures_et_demie..mp3" },
  { french: "Il est trois heures moins le quart.", english: "It is a quarter to three.", audio: "244_Il_est_trois_heures_moins_le_quart..mp3" },
  { french: "Il est minuit.", english: "It is midnight.", audio: "245_Il_est_minuit..mp3" },
  { french: "Il est midi.", english: "It is noon.", audio: "246_Il_est_midi..mp3" },
  { french: "Il fait mauvais.", english: "It is bad weather.", audio: "247_Il_fait_mauvais..mp3" },
  { french: "Il fait doux.", english: "It is mild.", audio: "248_Il_fait_doux..mp3" },
  { french: "Il fait froid.", english: "It is cold.", audio: "249_Il_fait_froid..mp3" },
  { french: "Il fait frais.", english: "It is cool.", audio: "250_Il_fait_frais..mp3" },
  { french: "Il y a des nuages.", english: "It is cloudy.", audio: "251_Il_y_a_des_nuages..mp3" },
  { french: "Il pleut.", english: "It is raining.", audio: "252_Il_pleut..mp3" },
  { french: "Il y a beaucoup de musées à Paris.", english: "There are many museums in Paris.", audio: "253_Il_y_a_beaucoup_de_musées_à_Paris..mp3" },
  { french: "Il arrive souvent des catastrophes naturelles dans ce pays.", english: "Natural disasters often happen in this country.", audio: "254_Il_arrive_souvent_des_catastrophes_natur.mp3" },
  { french: "Il faut prononcer clairement.", english: "You must pronounce clearly.", audio: "255_Il_faut_prononcer_clairement..mp3" },
  { french: "Il ne faut pas fumer ici.", english: "You must not smoke here.", audio: "256_Il_ne_faut_pas_fumer_ici..mp3" },
  { french: "Il faut de la viande pour faire cette recette.", english: "You need meat to make this recipe.", audio: "257_Il_faut_de_la_viande_pour_faire_cette_re.mp3" },
  { french: "Il paraît qu'elle va partir en France pour étudier.", english: "It seems she is going to France to study.", audio: "258_Il_paraît_qu'elle_va_partir_en_France_po.mp3" },
  { french: "Il est difficile d'apprendre plusieurs langues en même temps.", english: "It is difficult to learn several languages at the same time.", audio: "259_Il_est_difficile_d'apprendre_plusieurs_l.mp3" },
  { french: "C'est difficile d'apprendre plusieurs langues en même temps.", english: "It is difficult to learn several languages at the same time.", audio: "260_C'est_difficile_d'apprendre_plusieurs_la.mp3" },
  { french: "un vélo", english: "a bicycle", audio: "261_un_vélo.mp3" },
  { french: "des vélos", english: "bicycles", audio: "262_des_vélos.mp3" },
  { french: "une voiture", english: "a car", audio: "263_une_voiture.mp3" },
  { french: "des voitures", english: "cars", audio: "264_des_voitures.mp3" },
  { french: "le père de Paul", english: "Paul's father", audio: "265_le_père_de_Paul.mp3" },
  { french: "la Terre", english: "the Earth", audio: "266_la_Terre.mp3" },
  { french: "les États-Unis", english: "the United States", audio: "267_les_États-Unis.mp3" },
  { french: "le vin", english: "wine", audio: "268_le_vin.mp3" },
  { french: "l'amour", english: "love", audio: "269_l'amour.mp3" },
  { french: "les fruits", english: "fruits", audio: "270_les_fruits.mp3" },
  { french: "du vin", english: "wine", audio: "271_du_vin.mp3" },
  { french: "de la bière", english: "beer", audio: "272_de_la_bière.mp3" },
  { french: "de l'argent", english: "money", audio: "273_de_l'argent.mp3" },
  { french: "de l'eau", english: "water", audio: "274_de_l'eau.mp3" },
  { french: "un ami", english: "a friend", audio: "275_un_ami.mp3" },
  { french: "des hôtels", english: "hotels", audio: "276_des_hôtels.mp3" },
  { french: "une amie", english: "a friend", audio: "277_une_amie.mp3" },
  { french: "les étudiants", english: "students", audio: "278_les_étudiants.mp3" },
  { french: "Voici un stylo.", english: "Here is a pen.", audio: "279_Voici_un_stylo..mp3" },
  { french: "Voici des stylos.", english: "Here are pens.", audio: "280_Voici_des_stylos..mp3" },
  { french: "Voilà une feuille.", english: "There is a sheet.", audio: "281_Voilà_une_feuille..mp3" },
  { french: "Voilà des feuilles.", english: "There are sheets.", audio: "282_Voilà_des_feuilles..mp3" },
  { french: "Voici Paul.", english: "Here is Paul.", audio: "283_Voici_Paul..mp3" },
  { french: "Voilà le Louvre.", english: "There is the Louvre.", audio: "284_Voilà_le_Louvre..mp3" },
  { french: "C'est un restaurant.", english: "It is a restaurant.", audio: "285_C'est_un_restaurant..mp3" },
  { french: "C'est de l'eau.", english: "It is water.", audio: "286_C'est_de_l'eau..mp3" },
  { french: "Ce sont des restaurants.", english: "These are restaurants.", audio: "287_Ce_sont_des_restaurants..mp3" },
  { french: "Il y a un livre sur la table.", english: "There is a book on the table.", audio: "288_Il_y_a_un_livre_sur_la_table..mp3" },
  { french: "Il y a des livres sur la table.", english: "There are books on the table.", audio: "289_Il_y_a_des_livres_sur_la_table..mp3" },
  { french: "Je vais chercher Marie à l'aéroport.", english: "I am going to pick up Marie at the airport.", audio: "290_Je_vais_chercher_Marie_à_l'aéroport..mp3" },
  { french: "Je viens souvent ici prendre un café.", english: "I often come here to have a coffee.", audio: "291_Je_viens_souvent_ici_prendre_un_café..mp3" },
  { french: "C'est au bout de cette rue.", english: "It is at the end of this street.", audio: "292_C'est_au_bout_de_cette_rue..mp3" },
  { french: "C'est en face du cinéma.", english: "It is opposite the cinema.", audio: "293_C'est_en_face_du_cinéma..mp3" },
  { french: "C'est loin des Champs-Élysées.", english: "It is far from the Champs-Élysées.", audio: "294_C'est_loin_des_Champs-Élysées..mp3" },
  { french: "à la mer", english: "to the sea", audio: "295_à_la_mer.mp3" },
  { french: "à l'école", english: "to school", audio: "296_à_l'école.mp3" },
  { french: "de la gare", english: "from the train station", audio: "297_de_la_gare.mp3" },
  { french: "de l'hôpital", english: "from the hospital", audio: "298_de_l'hôpital.mp3" },
  { french: "Parce que j'ai de la fièvre.", english: "Because I have a fever.", audio: "299_Parce_que_j'ai_de_la_fièvre..mp3" },
  { french: "C'est quand, ton anniversaire ?", english: "When is your birthday?", audio: "300_C'est_quand_ton_anniversaire.mp3" },
  { french: "Elle est comment, son amie ?", english: "What is her friend like?", audio: "301_Elle_est_comment_son_amie.mp3" },
  { french: "Pourquoi tu ne sors pas ?", english: "Why don't you go out?", audio: "302_Pourquoi_tu_ne_sors_pas.mp3" },
  { french: "C'est combien, ce livre ?", english: "How much is this book?", audio: "303_C'est_combien_ce_livre.mp3" },
  { french: "Tu as combien de cours demain ?", english: "How many classes do you have tomorrow?", audio: "304_Tu_as_combien_de_cours_demain.mp3" },
  { french: "Que faites-vous dans la vie ?", english: "What do you do for a living?", audio: "305_Que_faites-vous_dans_la_vie.mp3" },
  { french: "Je suis avocat.", english: "I am a lawyer.", audio: "306_Je_suis_avocat..mp3" },
  { french: "Qui est premier en anglais ?", english: "Who is first in English?", audio: "307_Qui_est_premier_en_anglais.mp3" },
  { french: "C'est Vincent.", english: "It's Vincent.", audio: "308_C'est_Vincent..mp3" },
  { french: "Cette robe est en quoi ?", english: "What is this dress made of?", audio: "309_Cette_robe_est_en_quoi.mp3" },
  { french: "Elle est en soie.", english: "It is made of silk.", audio: "310_Elle_est_en_soie..mp3" },
  { french: "Qui tu aimes comme poète ?", english: "Which poet do you like?", audio: "311_Qui_tu_aimes_comme_poète.mp3" },
  { french: "J'aime Jacques Prévert.", english: "I like Jacques Prévert.", audio: "312_J'aime_Jacques_Prévert..mp3" },
  { french: "Avec qui tu sors ?", english: "Who are you going out with?", audio: "313_Avec_qui_tu_sors.mp3" },
  { french: "Je sors avec Rose.", english: "I'm going out with Rose.", audio: "314_Je_sors_avec_Rose..mp3" },
  { french: "Qu'est-ce que vous prenez comme boisson ?", english: "What would you like to drink?", audio: "315_Qu'est-ce_que_vous_prenez_comme_boisson.mp3" },
  { french: "Une eau minérale, s'il vous plaît.", english: "A mineral water, please.", audio: "316_Une_eau_minérale_s'il_vous_plaît..mp3" },
  { french: "Ce sont des applications.", english: "These are applications.", audio: "317_Ce_sont_des_applications..mp3" },
  { french: "Qu'est-ce que c'est ?", english: "What is it?", audio: "318_Qu'est-ce_que_c'est.mp3" },
  { french: "Ce sont les parents de Julia.", english: "They are Julia's parents.", audio: "319_Ce_sont_les_parents_de_Julia..mp3" },
  { french: "Qui est-ce ?", english: "Who is it?", audio: "320_Qui_est-ce.mp3" },
  { french: "Il fait du foot.", english: "He plays football.", audio: "321_Il_fait_du_foot..mp3" },
  { french: "Il fait quoi comme sport ?", english: "What sport does he play?", audio: "322_Il_fait_quoi_comme_sport.mp3" },
  { french: "Maria peut répondre à la question.", english: "Maria can answer the question.", audio: "323_Maria_peut_répondre_à_la_question..mp3" },
  { french: "Qui peut répondre à la question ?", english: "Who can answer the question?", audio: "324_Qui_peut_répondre_à_la_question.mp3" },
  { french: "Il parle avec Marie au téléphone.", english: "He is talking with Marie on the phone.", audio: "325_Il_parle_avec_Marie_au_téléphone..mp3" },
  { french: "Avec qui parle-t-il au téléphone ?", english: "Who is he talking with on the phone?", audio: "326_Avec_qui_parle-t-il_au_téléphone.mp3" },
  { french: "Ils discutent de leur projet de voyage.", english: "They are discussing their travel plans.", audio: "327_Ils_discutent_de_leur_projet_de_voyage..mp3" },
  { french: "De quoi discutent-ils ?", english: "What are they discussing?", audio: "328_De_quoi_discutent-ils.mp3" },
  { french: "Laquelle de ces voitures est à vous ?", english: "Which of these cars is yours?", audio: "329_Laquelle_de_ces_voitures_est_à_vous.mp3" },
  { french: "C'est la blanche.", english: "It's the white one.", audio: "330_C'est_la_blanche..mp3" },
  { french: "Parmi ces acteurs, lequel joue le rôle principal ?", english: "Among these actors, which one plays the main role?", audio: "331_Parmi_ces_acteurs_lequel_joue_le_rôle_principal.mp3" },
  { french: "C'est Fabrice Luchini.", english: "It's Fabrice Luchini.", audio: "332_C'est_Fabrice_Luchini..mp3" },
  { french: "De ces vêtements, lesquels sont pour l'hiver ?", english: "Of these clothes, which ones are for winter?", audio: "333_De_ces_vêtements_lesquels_sont_pour_l'hiver.mp3" },
  { french: "Ceux-là.", english: "Those ones.", audio: "334_Ceux-là..mp3" },
  { french: "Parmi ces chaussures, lesquelles vas-tu choisir ?", english: "Among these shoes, which ones are you going to choose?", audio: "335_Parmi_ces_chaussures_lesquelles_vas-tu_choisir.mp3" },
  { french: "Je préfère ces chaussures de marche.", english: "I prefer these walking shoes.", audio: "336_Je_préfère_ces_chaussures_de_marche..mp3" },
  { french: "C'est Pascal qui veut étudier au Japon.", english: "It's Pascal who wants to study in Japan.", audio: "337_C'est_Pascal_qui_veut_étudier_au_Japon..mp3" },
  { french: "C'est au Japon que Pascal veut étudier.", english: "It's in Japan that Pascal wants to study.", audio: "338_C'est_au_Japon_que_Pascal_veut_étudier..mp3" },
  { french: "Qui chante là ?", english: "Who is singing there?", audio: "339_Qui_chante_là.mp3" },
  { french: "C'est Rose.", english: "It's Rose.", audio: "340_C'est_Rose..mp3" },
  { french: "Qu'est-ce que tu prends comme dessert ?", english: "What are you having for dessert?", audio: "341_Qu'est-ce_que_tu_prends_comme_dessert.mp3" },
  { french: "Va tout de suite chez lui.", english: "Go to his place right away.", audio: "342_Va_tout_de_suite_chez_lui..mp3" },
  { french: "Ayons du courage.", english: "Let's have courage.", audio: "343_Ayons_du_courage..mp3" },
  { french: "Soyez gentils avec vos parents.", english: "Be kind to your parents.", audio: "344_Soyez_gentils_avec_vos_parents..mp3" },
  { french: "Ne dis pas ça à Léo.", english: "Don't say that to Léo.", audio: "345_Ne_dis_pas_ça_à_Léo..mp3" },
  { french: "Ne parlons plus de ça.", english: "Let's not talk about that anymore.", audio: "346_Ne_parlons_plus_de_ça..mp3" },
  { french: "Faites comme chez vous.", english: "Make yourself at home.", audio: "347_Faites_comme_chez_vous..mp3" },
  { french: "Quels sont ces arbres ? Ce sont des baobabs.", english: "What are these trees? They are baobabs.", audio: "348_Quels_sont_ces_arbres_Ce_sont_des_baobabs..mp3" },
  { french: "Quel jour sommes-nous ? Samedi.", english: "What day is it? Saturday.", audio: "349_Quel_jour_sommes-nous_Samedi..mp3" },
  { french: "Quelles matières aime-t-il ? Il aime la chimie et la musique.", english: "Which subjects does he like? He likes chemistry and music.", audio: "350_Quelles_matières_aime-t-il_Il_aime_la_chimie_et_la_musique..mp3" },
  { french: "Quelle cuisine aimez-vous ? J'aime la cuisine italienne.", english: "What cuisine do you like? I like Italian cuisine.", audio: "351_Quelle_cuisine_aimez-vous_J'aime_la_cuisine_italienne..mp3" },
  { french: "Quel est ton livre préféré ? Le Rouge et le Noir de Stendhal.", english: "What is your favorite book? The Red and the Black by Stendhal.", audio: "352_Quel_est_ton_livre_préféré_Le_Rouge_et_le_Noir_de_Stendhal..mp3" },
  { french: "Quel est ton passe-temps favori ? C'est la pêche.", english: "What is your favorite hobby? It's fishing.", audio: "353_Quel_est_ton_passe-temps_favori_C'est_la_pêche..mp3" },
  { french: "Il fait très chaud aujourd'hui.", english: "It is very hot today.", audio: "354_Il_fait_très_chaud_aujourd'hui..mp3" },
  { french: "Il faut faire des efforts pour réussir.", english: "You must make efforts to succeed.", audio: "355_Il_faut_faire_des_efforts_pour_réussir..mp3" },
  { french: "Il paraît que Sylvie sort avec Patrick.", english: "It seems that Sylvie is going out with Patrick.", audio: "356_Il_paraît_que_Sylvie_sort_avec_Patrick..mp3" },
  { french: "Il y a une épicerie à côté de chez moi.", english: "There is a grocery store next to my place.", audio: "357_Il_y_a_une_épicerie_à_côté_de_chez_moi..mp3" },
  { french: "Il arrive fréquemment des retards sur cette ligne.", english: "Delays frequently occur on this line.", audio: "358_Il_arrive_fréquemment_des_retards_sur_cette_ligne..mp3" },
  { french: "Il est nécessaire de réfléchir avant de décider.", english: "It is necessary to think before deciding.", audio: "359_Il_est_nécessaire_de_réfléchir_avant_de_décider..mp3" },
  { french: "Quelle est sa profession ?", english: "What is his profession?", audio: "360_Quelle_est_sa_profession.mp3" },
  { french: "Il fait beau aujourd'hui.", english: "The weather is nice today.", audio: "361_Il_fait_beau_aujourd'hui..mp3" },
  { french: "Tu vas en Suisse ?", english: "Are you going to Switzerland?", audio: "362_Tu_vas_en_Suisse.mp3" },
  { french: "Il vient des Pays-Bas.", english: "He comes from the Netherlands.", audio: "363_Il_vient_des_Pays-Bas..mp3" },
  { french: "Nous allons au Japon.", english: "We are going to Japan.", audio: "364_Nous_allons_au_Japon..mp3" },
  { french: "Ils viennent d'Angleterre.", english: "They come from England.", audio: "365_Ils_viennent_d'Angleterre..mp3" },
  { french: "Je vais avoir vingt ans.", english: "I am going to be twenty years old.", audio: "366_Je_vais_avoir_vingt_ans..mp3" },
  { french: "Il vient d'arriver.", english: "He just arrived.", audio: "367_Il_vient_d'arriver..mp3" },
  { french: "Nous venons de finir ce travail.", english: "We just finished this work.", audio: "368_Nous_venons_de_finir_ce_travail..mp3" },
  { french: "J'ai mal aux dents.", english: "I have a toothache.", audio: "369_J'ai_mal_aux_dents..mp3" },
  { french: "C'est loin du Louvre.", english: "It is far from the Louvre.", audio: "370_C'est_loin_du_Louvre..mp3" },
  { french: "C'est à côté des Invalides.", english: "It is next to the Invalides.", audio: "371_C'est_à_côté_des_Invalides..mp3" },
  { french: "Je préfère le café au thé.", english: "I prefer coffee to tea.", audio: "372_Je_préfère_le_café_au_thé..mp3" },
  { french: "Où est l'Opéra ? C'est tout droit.", english: "Where is the Opera? It's straight ahead.", audio: "373_Où_est_l'Opéra_C'est_tout_droit..mp3" },
  { french: "Ça fait combien ? Quinze euros vingt.", english: "How much is it? Fifteen euros twenty.", audio: "374_Ça_fait_combien_Quinze_euros_vingt..mp3" },
  { french: "Vous partez quand ? Demain matin.", english: "When are you leaving? Tomorrow morning.", audio: "375_Vous_partez_quand_Demain_matin..mp3" },
  { french: "Pourquoi tu es si content ? Parce que cet après-midi on n'a pas cours.", english: "Why are you so happy? Because this afternoon we don't have class.", audio: "376_Pourquoi_tu_es_si_content_Parce_que_cet_après-midi_on_n'a_pas_cours..mp3" },
  { french: "Sa cousine est comment ? Elle est sympa.", english: "What is his cousin like? She is nice.", audio: "377_Sa_cousine_est_comment_Elle_est_sympa..mp3" },
  { french: "Il y a combien de pièces ? Cinq.", english: "How many rooms are there? Five.", audio: "378_Il_y_a_combien_de_pièces_Cinq..mp3" },
  { french: "Quand arrive-t-elle ?", english: "When does she arrive?", audio: "379_Quand_arrive-t-elle.mp3" },
  { french: "Tu mesures combien ?", english: "How tall are you?", audio: "380_Tu_mesures_combien.mp3" },
  { french: "Comment allez-vous à la fac ?", english: "How do you go to the university?", audio: "381_Comment_allez-vous_à_la_fac.mp3" },
  { french: "Pourquoi est-il absent ?", english: "Why is he absent?", audio: "382_Pourquoi_est-il_absent.mp3" },
  { french: "Où sont les toilettes ?", english: "Where is the restroom?", audio: "383_Où_sont_les_toilettes.mp3" },
  { french: "Combien de temps mets-tu pour venir ici ?", english: "How long does it take you to come here?", audio: "384_Combien_de_temps_mets-tu_pour_venir_ici.mp3" },
  { french: "Où vas-tu demain ?", english: "Where are you going tomorrow?", audio: "385_Où_vas-tu_demain.mp3" },
  { french: "Je viens d'arriver.", english: "I just arrived.", audio: "386_Je_viens_d'arriver..mp3" },
  { french: "Elle ne boit pas de lait.", english: "She doesn't drink milk.", audio: "387_Elle_ne_boit_pas_de_lait..mp3" },
  { french: "Il n'y a pas de cinémas.", english: "There are no cinemas.", audio: "388_Il_n'y_a_pas_de_cinémas..mp3" },
  { french: "Nous ne prenons pas de taxi.", english: "We don't take a taxi.", audio: "389_Nous_ne_prenons_pas_de_taxi..mp3" },
  { french: "Je ne fais pas de danse.", english: "I don't do dance.", audio: "390_Je_ne_fais_pas_de_danse..mp3" },
  { french: "Ce n'est pas un ordinateur.", english: "It is not a computer.", audio: "391_Ce_n'est_pas_un_ordinateur..mp3" },
  { french: "Ils n'aiment pas les voyages.", english: "They don't like traveling.", audio: "392_Ils_n'aiment_pas_les_voyages..mp3" },
  { french: "Est-ce que c'est du vin ?", english: "Is it wine?", audio: "393_Est-ce_que_c'est_du_vin.mp3" },
  { french: "Est-ce que ta mère travaille ?", english: "Does your mother work?", audio: "394_Est-ce_que_ta_mère_travaille.mp3" },
  { french: "Est-ce qu'elle a des amis français ?", english: "Does she have French friends?", audio: "395_Est-ce_qu'elle_a_des_amis_français.mp3" },
  { french: "Y a-t-il une supérette ?", english: "Is there a convenience store?", audio: "396_Y_a-t-il_une_supérette.mp3" },
  { french: "Pascal habite-t-il à Bordeaux ?", english: "Does Pascal live in Bordeaux?", audio: "397_Pascal_habite-t-il_à_Bordeaux.mp3" },
  { french: "Ces stylos sont-ils chers ?", english: "Are these pens expensive?", audio: "398_Ces_stylos_sont-ils_chers.mp3" },
  { french: "Non, ce n'est pas du sel.", english: "No, it is not salt.", audio: "399_Non_ce_n'est_pas_du_sel..mp3" },
  { french: "Non, il n'y a pas d'eau.", english: "No, there is no water.", audio: "400_Non_il_n'y_a_pas_d'eau..mp3" },
  { french: "Oui, j'ai deux cours.", english: "Yes, I have two classes.", audio: "401_Oui_j'ai_deux_cours..mp3" },
  { french: "Si, j'aime beaucoup étudier.", english: "Yes, I really like studying.", audio: "402_Si_j'aime_beaucoup_étudier..mp3" },
  { french: "Non, ce n'est pas mon portable.", english: "No, it is not my cell phone.", audio: "403_Non_ce_n'est_pas_mon_portable..mp3" },
  { french: "Si, il y a un café là-bas.", english: "Yes, there is a cafe over there.", audio: "404_Si_il_y_a_un_café_là-bas..mp3" },
  { french: "Ce n'est pas de l'eau.", english: "It is not water.", audio: "405_Ce_n'est_pas_de_l'eau..mp3" },
  { french: "Il n'y a plus de lait.", english: "There is no more milk.", audio: "406_Il_n'y_a_plus_de_lait..mp3" },
  { french: "J'obéis à mes parents.", english: "I obey my parents.", audio: "407_J'obéis_à_mes_parents..mp3" },
  { french: "Tu réussis dans la vie !", english: "You succeed in life!", audio: "408_Tu_réussis_dans_la_vie.mp3" },
  { french: "Vous remplissez cette fiche, s'il vous plaît.", english: "Please fill out this form.", audio: "409_Vous_remplissez_cette_fiche_s'il_vous_plaît..mp3" },
  { french: "Les enfants grandissent vite.", english: "Children grow up fast.", audio: "410_Les_enfants_grandissent_vite..mp3" },
  { french: "Ce parc embellit d'année en année.", english: "This park becomes more beautiful year by year.", audio: "411_Ce_parc_embellit_d'année_en_année..mp3" },
  { french: "Nous choisissons le menu à vingt euros.", english: "We choose the twenty-euro menu.", audio: "412_Nous_choisissons_le_menu_à_vingt_euros..mp3" },
  { french: "Je suis libre ce soir.", english: "I am free tonight.", audio: "413_Je_suis_libre_ce_soir..mp3" },
  { french: "Ces gâteaux sont très bons.", english: "These cakes are very good.", audio: "414_Ces_gâteaux_sont_très_bons..mp3" },
  { french: "J'achète ces chaussures.", english: "I am buying these shoes.", audio: "415_J'achète_ces_chaussures..mp3" },
  { french: "Il est très occupé cet après-midi.", english: "He is very busy this afternoon.", audio: "416_Il_est_très_occupé_cet_après-midi..mp3" },
  { french: "Je préfère ce livre-ci à ce livre-là.", english: "I prefer this book to that book.", audio: "417_Je_préfère_ce_livre-ci_à_ce_livre-là..mp3" },
  { french: "J'aime beaucoup cette couleur.", english: "I really like this color.", audio: "418_J'aime_beaucoup_cette_couleur..mp3" },
  { french: "C'est le passeport de Léa ? Oui, c'est son passeport.", english: "Is it Léa's passport? Yes, it's her passport.", audio: "419_C'est_le_passeport_de_Léa_Oui_c'est_son_passeport..mp3" },
  { french: "C'est la voiture de Pierre ? Oui, c'est sa voiture.", english: "Is it Pierre's car? Yes, it's his car.", audio: "420_C'est_la_voiture_de_Pierre_Oui_c'est_sa_voiture..mp3" },
  { french: "C'est votre ville ? Oui, c'est notre ville.", english: "Is it your city? Yes, it's our city.", audio: "421_C'est_votre_ville_Oui_c'est_notre_ville..mp3" },
  { french: "Ce sont les parents de Pierre et de Jeanne ? Oui, ce sont leurs parents.", english: "Are they Pierre and Jeanne's parents? Yes, they are their parents.", audio: "422_Ce_sont_les_parents_de_Pierre_et_de_Jeanne_Oui_ce_sont_leurs_parents..mp3" },
  { french: "Ce sac est à toi ? Oui, il est à moi. C'est mon sac.", english: "Is this bag yours? Yes, it's mine. It's my bag.", audio: "423_Ce_sac_est_à_toi_Oui_il_est_à_moi_C'est_mon_sac..mp3" },
  { french: "Cette maison est à vous ? Oui, elle est à nous. C'est notre maison.", english: "Is this house yours? Yes, it's ours. It's our house.", audio: "424_Cette_maison_est_à_vous_Oui_elle_est_à_nous_C'est_notre_maison..mp3" },
  { french: "Ces stylos sont à Emma ? Oui, ils sont à elle. Ce sont ses stylos.", english: "Are these pens Emma's? Yes, they are hers. They are her pens.", audio: "425_Ces_stylos_sont_à_Emma_Oui_ils_sont_à_elle_Ce_sont_ses_stylos..mp3" },
  { french: "Cet appartement est à tes parents ? Oui, il est à eux. C'est leur appartement.", english: "Is this apartment your parents'? Yes, it's theirs. It's their apartment.", audio: "426_Cet_appartement_est_à_tes_parents_Oui_il_est_à_eux_C'est_leur_appartement..mp3" },
  { french: "Je choisis ce livre.", english: "I choose this book.", audio: "427_Je_choisis_ce_livre..mp3" },
  { french: "Ce stylo est à toi ?", english: "Is this pen yours?", audio: "428_Ce_stylo_est_à_toi.mp3" },
  { french: "J'arrive bientôt.", english: "I am arriving soon.", audio: "429_J'arrive_bientôt..mp3" },
  { french: "Pierre cherche du travail.", english: "Pierre is looking for work.", audio: "430_Pierre_cherche_du_travail..mp3" },
  { french: "Tu chantes très bien !", english: "You sing very well!", audio: "431_Tu_chantes_très_bien.mp3" },
  { french: "Vous habitez à Bordeaux ?", english: "Do you live in Bordeaux?", audio: "432_Vous_habitez_à_Bordeaux.mp3" },
  { french: "Ils écoutent de la musique.", english: "They are listening to music.", audio: "433_Ils_écoutent_de_la_musique..mp3" },
  { french: "Nous voyageons en France.", english: "We are traveling in France.", audio: "434_Nous_voyageons_en_France..mp3" },
  { french: "Tu préfères un thé ou un café ?", english: "Do you prefer tea or coffee?", audio: "435_Tu_préfères_un_thé_ou_un_café.mp3" },
  { french: "Je travaille dans une supérette.", english: "I work in a convenience store.", audio: "436_Je_travaille_dans_une_supérette..mp3" },
  { french: "Elles regardent beaucoup la télé.", english: "They watch TV a lot.", audio: "437_Elles_regardent_beaucoup_la_télé..mp3" },
  { french: "Marie achète une baguette chaque matin.", english: "Marie buys a baguette every morning.", audio: "438_Marie_achète_une_baguette_chaque_matin..mp3" },
  { french: "Une belle vue.", english: "A beautiful view.", audio: "439_Une_belle_vue..mp3" },
  { french: "Une actrice italienne.", english: "An Italian actress.", audio: "440_Une_actrice_italienne..mp3" },
  { french: "Une bonne idée.", english: "A good idea.", audio: "441_Une_bonne_idée..mp3" },
  { french: "Une robe blanche.", english: "A white dress.", audio: "442_Une_robe_blanche..mp3" },
  { french: "Une fleur jaune.", english: "A yellow flower.", audio: "443_Une_fleur_jaune..mp3" },
  { french: "Une fille sportive.", english: "A sporty girl.", audio: "444_Une_fille_sportive..mp3" },
  { french: "De vieux amis.", english: "Old friends.", audio: "445_De_vieux_amis..mp3" },
  { french: "Des livres difficiles.", english: "Difficult books.", audio: "446_Des_livres_difficiles..mp3" },
  { french: "Des stylos français.", english: "French pens.", audio: "447_Des_stylos_français..mp3" },
  { french: "De beaux arbres.", english: "Beautiful trees.", audio: "448_De_beaux_arbres..mp3" },
  { french: "Des manteaux gris.", english: "Gray coats.", audio: "449_Des_manteaux_gris..mp3" },
  { french: "De nouveaux magasins.", english: "New stores.", audio: "450_De_nouveaux_magasins..mp3" },
  { french: "J'aime beaucoup le cinéma.", english: "I really like cinema.", audio: "451_J'aime_beaucoup_le_cinéma..mp3" },
  { french: "C'est un livre rouge.", english: "It's a red book.", audio: "452_C'est_un_livre_rouge..mp3" },
  { french: "Je suis à Paris.", english: "I am in Paris.", audio: "453_Je_suis_à_Paris..mp3" },
  { french: "On est le 2 juillet aujourd'hui.", english: "Today is July 2nd.", audio: "454_On_est_le_2_juillet_aujourd'hui..mp3" },
  { french: "Nous sommes quatre.", english: "There are four of us.", audio: "455_Nous_sommes_quatre..mp3" },
  { french: "Ce sont les parents de Pierre.", english: "They are Pierre's parents.", audio: "456_Ce_sont_les_parents_de_Pierre..mp3" },
  { french: "Vous êtes de Bordeaux ?", english: "Are you from Bordeaux?", audio: "457_Vous_êtes_de_Bordeaux.mp3" },
  { french: "Ils ont quinze ans.", english: "They are fifteen years old.", audio: "458_Ils_ont_quinze_ans..mp3" },
  { french: "Tu as mal à la tête ?", english: "Do you have a headache?", audio: "459_Tu_as_mal_à_la_tête.mp3" },
  { french: "Il y a une supérette près d'ici ?", english: "Is there a convenience store nearby?", audio: "460_Il_y_a_une_supérette_près_d'ici.mp3" },
  { french: "Nous avons deux cours de français par semaine.", english: "We have two French classes per week.", audio: "461_Nous_avons_deux_cours_de_français_par_semaine..mp3" },
  { french: "J'ai envie d'une glace.", english: "I feel like having an ice cream.", audio: "462_J'ai_envie_d'une_glace..mp3" },
  { french: "Tu as une moto ? Non, mais j'ai un skateboard.", english: "Do you have a motorcycle? No, but I have a skateboard.", audio: "463_Tu_as_une_moto_Non_mais_j'ai_un_skateboard..mp3" },
  { french: "Elle est japonaise ? Oui, elle est japonaise.", english: "Is she Japanese? Yes, she is Japanese.", audio: "464_Elle_est_japonaise_Oui_elle_est_japonaise..mp3" },
  { french: "Jean est étudiant ? Non, il est lycéen.", english: "Is Jean a university student? No, he is a high school student.", audio: "465_Jean_est_étudiant_Non_il_est_lycéen..mp3" },
  { french: "Sophie a des enfants ? Oui, elle a deux enfants.", english: "Does Sophie have children? Yes, she has two children.", audio: "466_Sophie_a_des_enfants_Oui_elle_a_deux_enfants..mp3" },
  { french: "Vous êtes journaliste ? Non, je suis photographe.", english: "Are you a journalist? No, I am a photographer.", audio: "467_Vous_êtes_journaliste_Non_je_suis_photographe..mp3" },
  { french: "Vous avez faim ? Non, mais nous avons soif.", english: "Are you hungry? No, but we are thirsty.", audio: "468_Vous_avez_faim_Non_mais_nous_avons_soif..mp3" },
  { french: "Nicolas et Pascal sont frères ? Oui, ils sont frères.", english: "Are Nicolas and Pascal brothers? Yes, they are brothers.", audio: "469_Nicolas_et_Pascal_sont_frères_Oui_ils_sont_frères..mp3" },
  { french: "Chloé et Thomas ont un chat ? Oui, ils ont un chat.", english: "Do Chloé and Thomas have a cat? Yes, they have a cat.", audio: "470_Chloé_et_Thomas_ont_un_chat_Oui_ils_ont_un_chat..mp3" },
  { french: "Il est français.", english: "He is French.", audio: "471_Il_est_français..mp3" },
  { french: "Vous avez raison.", english: "You are right.", audio: "472_Vous_avez_raison..mp3" },
  { french: "un sac", english: "a bag", audio: "473_un_sac.mp3" },
  { french: "une montre", english: "a watch", audio: "474_une_montre.mp3" },
  { french: "un croissant", english: "a croissant", audio: "475_un_croissant.mp3" },
  { french: "un hôtel", english: "a hotel", audio: "476_un_hôtel.mp3" },
  { french: "une baguette", english: "a baguette", audio: "477_une_baguette.mp3" },
  { french: "des arbres", english: "trees", audio: "478_des_arbres.mp3" },
  { french: "des oranges", english: "oranges", audio: "479_des_oranges.mp3" },
  { french: "une église", english: "a church", audio: "480_une_église.mp3" },
  { french: "la maison de Paul", english: "Paul's house", audio: "481_la_maison_de_Paul.mp3" },
  { french: "l'école de Mari", english: "Mari's school", audio: "482_l'école_de_Mari.mp3" },
  { french: "le Japon", english: "Japan", audio: "483_le_Japon.mp3" },
  { french: "la France", english: "France", audio: "484_la_France.mp3" },
  { french: "la musique", english: "music", audio: "485_la_musique.mp3" },
  { french: "l'opéra", english: "opera", audio: "486_l'opéra.mp3" },
  { french: "les légumes", english: "vegetables", audio: "487_les_légumes.mp3" },
  { french: "les parents de Jean", english: "Jean's parents", audio: "488_les_parents_de_Jean.mp3" },
  { french: "Il y a du poisson.", english: "There is fish.", audio: "489_Il_y_a_du_poisson..mp3" },
  { french: "Il y a de l'huile.", english: "There is oil.", audio: "490_Il_y_a_de_l'huile..mp3" },
  { french: "Il y a du beurre.", english: "There is butter.", audio: "491_Il_y_a_du_beurre..mp3" },
  { french: "Il y a de la moutarde.", english: "There is mustard.", audio: "492_Il_y_a_de_la_moutarde..mp3" },
  { french: "Il y a de la viande.", english: "There is meat.", audio: "493_Il_y_a_de_la_viande..mp3" },
  { french: "Il y a de la confiture.", english: "There is jam.", audio: "494_Il_y_a_de_la_confiture..mp3" },
  { french: "Il y a de l'ail.", english: "There is garlic.", audio: "495_Il_y_a_de_l'ail..mp3" },
  { french: "Il y a du vinaigre.", english: "There is vinegar.", audio: "496_Il_y_a_du_vinaigre..mp3" },
  { french: "Voici un citron.", english: "Here is a lemon.", audio: "497_Voici_un_citron..mp3" },
  { french: "Voilà la tour Eiffel.", english: "There is the Eiffel Tower.", audio: "498_Voilà_la_tour_Eiffel..mp3" },
  { french: "C'est de l'eau.", english: "It is water.", audio: "499_C'est_de_l'eau..mp3" },
  { french: "Ce sont des escargots.", english: "These are snails.", audio: "500_Ce_sont_des_escargots..mp3" },
  { french: "Il y a du lait dans le frigo.", english: "There is milk in the fridge.", audio: "501_Il_y_a_du_lait_dans_le_frigo..mp3" },
  { french: "Le lait est bon pour la santé.", english: "Milk is good for your health.", audio: "502_Le_lait_est_bon_pour_la_santé..mp3" },
  { french: "C'est un stylo.", english: "It is a pen.", audio: "503_C'est_un_stylo..mp3" },
  { french: "Ce sont des légumes.", english: "These are vegetables.", audio: "504_Ce_sont_des_légumes..mp3" }
];